RedHatProductSecurity/osim

.dockerignore
.github/workflows/deploy_images_to_ghcr.yaml
.github/workflows/deploy_images_to_quay.yaml
Dockerfile
README.md
openshift/staging/00-image-stream.yaml
openshift/staging/10-deployment-config.yaml
openshift/staging/10-route.yaml
openshift/staging/10-service.yaml
src/components/IssueDetails.vue
src/components/IssueQueue.vue
src/components/ObjectArray.vue
src/views/FlawView.vue

Will require tweaking. Currently having trouble building with latest commits.

Simple container build and push test

---

package.json
src/components/FlawCreateForm.vue
src/components/IssueEdit.vue
src/components/IssueQueueItem.vue
src/components/Settings.vue
src/components/widgets/EditableDate.vue
src/components/widgets/Toast.vue
src/stores/ToastStore.ts
src/types/zodFlaw.ts
src/views/WidgetTestView.vue
yarn.lock

Osidb 1240

---

package.json
src/components/__tests__/ExampleForm.spec.ts
tsconfig.app.json
tsconfig.config.json
tsconfig.json
tsconfig.node.json
tsconfig.vitest.json
vitest.config.ts
yarn.lock

Add unit test scaffolding

---

src/components/IssueQueue.vue
src/services/FlawService.ts

Osidb 1116

---

src/components/FlawCreateForm.vue
src/components/IssueEdit.vue

Regarding "Adjust API call for flaw edit for major incidents"
FlawService.ts createFlaw type takes any... 
If enum matches, isn't it already adjusted? Do you want me to add typing to that function?

Osidb 1229

---

features/check_login.feature
features/constants.py
features/steps/check_login.py
features/steps/flaw.py
features/steps/load_more_flaws.py
features/steps/logout.py
features/utils.py

[OSIDB-1777](https://issues.redhat.com/browse/OSIDB-1777)

Update some xpath locaters to css_selector locaters

---

features/README.md
features/constants.py
features/flaw.feature
features/locators.py
features/steps/common_steps.py
features/steps/flaw.py
features/utils.py

[OSIDB-1861](https://issues.redhat.com/browse/OSIDB-1861)

Add public comment

---

features/locators.py
features/pages/home_page.py
features/steps/filter_flaws.py

[OSIDB-2069](https://issues.redhat.com/browse/OSIDB-2069)

Update flaw filter test cases to use page objects

---

src/assets/main.css
src/main.ts
src/scss/bootstap-overrides.scss
src/scss/bootstrap-overrides.scss

- Makes links not red but blue
- Adds success color

Supply missing pushed commits from Branding color updates

---

src/App.vue
src/components/Navbar.vue
src/components/ToastContainer.vue
src/components/__tests__/App.spec.ts
src/components/__tests__/Navbar.spec.ts
src/components/__tests__/ToastContainer.spec.ts
src/components/widgets/Toast.vue
src/components/widgets/__tests__/Toast.spec.ts
src/stores/SettingsStore.ts
src/stores/ToastStore.ts
src/stores/__tests__/SettingsStore.spec.ts
src/stores/__tests__/ToastStore.spec.ts

hiding notification after 10 seconds when showNotification if false and respective test cases

hiding notification after 10 seconds when showNotification if false and respective test cases

---

src/components/AffectedOfferings.vue
src/components/widgets/LabelCollapsable.vue
src/utils/helpers.ts

@d10n 
I think this is less bad :)

♻️ Simplify collapsible state management

---

src/components/IssueFieldAcknowledgments.vue
src/components/IssueFieldReferences.vue
src/components/widgets/EditableList.vue
src/composables/useModal.ts

🐛 Prevent overlapping modals

---

features/flaw_create.feature
features/pages/advanced_search_page.py
features/pages/flaw_detail_page.py
features/steps/flaw_create.py

[OSIDB-1825](https://issues.redhat.com/browse/OSIDB-1825)

Add test case for creating embargoed flaw

---

CHANGELOG.md
src/components/FlawForm.vue
src/components/Settings.vue
src/components/__tests__/FlawForm.spec.ts
src/components/widgets/EditableDate.vue
src/components/widgets/EditableText.vue
src/components/widgets/LabelInput.vue
src/components/widgets/LabelTextarea.vue

This PR:
* converts CVSS3 score to readonly fields
* makes Flaw Comment#0 writable only upon Flaw creation
Partially addresses OSIDB-2308

OSIDB-2308: Readonly Comment#0 and CVSS3 score

---

src/components/IssueQueue.vue

Remove input filter on IssueQueue Table

---

.github/pull_request_template.md
CONTRIBUTING.md

Provides documents for pull request description template and contribution guidelines.
- Adds `pull_request_template.md` to  `.github` dir
- Adds `contribution.md` to `/docs`
- Just a draft proposal for both documents, we can use this PR to discuss/adapt the info provided or huddle about it
- I think we should also update [OSIM Developer Guide](https://github.com/RedHatProductSecurity/osim/blob/doc/contribution-docs/docs/overview.md)
- Would be nice to extend [OSIM Developer Guide](https://github.com/RedHatProductSecurity/osim/blob/doc/contribution-docs/docs/overview.md) with some more information like `Ecosystem`, `Useful tools` ...

📝 Contribution documents

---

CHANGELOG.md
src/components/widgets/EditableDate.vue
src/components/widgets/__tests__/EditableDate.spec.ts
src/composables/useFlawModel.ts

🐛  Fix date component cancel/save buttons

---

CHANGELOG.md
src/components/IssueQueue.vue
src/components/__tests__/FlawSearchView.spec.ts
src/components/__tests__/IssueQueue.spec.ts
src/composables/__tests__/useFlaws.spec.ts
src/composables/__tests__/useSearchParams.spec.ts
src/composables/useFlaws.ts
src/views/FlawSearchView.vue
src/views/IndexView.vue

Add Total, Loaded Count for IssueQueue
Add Total Count for IssueQueue table

Add Total Count for IndexView, Search Page

---

CHANGELOG.md
package.json
src/components/AffectedOfferingForm.vue
src/components/FlawForm.vue
src/components/IssueQueue.vue
src/components/__tests__/FlawForm.spec.ts
src/composables/__tests__/useNetworkQueue.spec.ts
src/composables/service-helpers.ts
src/composables/useCvssScoresModel.ts
src/composables/useFlawAffectsModel.ts
src/composables/useFlawModel.ts
src/composables/useNetworkQueue.ts
src/services/AffectService.ts
src/services/FlawService.ts
src/services/OsidbAuthService.ts
src/stores/SettingsStore.ts
src/types/zodFlaw.ts
src/utils/helpers.ts
tsconfig.app.json
yarn.lock

Fixes bug with sequential save operations failing. (eg multiple affects for flaws)
- Replaces axios with fetch
- Refactors error handling and error boundaries
- Emulates certain parts of the axios API
- Adds global saving queue
- Test coverage for global queue
- When saving a flaw, fetches most recent flaw updated time (needed after any update to a flaw or dependent entity to prevent the outdated model error)
Removes axios, so every bit of testing is helpful

🐛 Fix outdated model instance errors on Flaws

---

src/components/IssueQueue.vue
src/components/IssueQueueItem.vue

Update column widths

---

features/flaw_detail.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py
features/utils.py

Add test case for deleting affect

---

CHANGELOG.md
src/components/FlawForm.vue
src/components/widgets/EditableDate.vue
src/components/widgets/LabelEditable.vue
src/components/widgets/__tests__/EditableDate.spec.ts

Support specifying a time when a flaw is to be unembargoed.
Simplified Date parsing and formatting
- Implementation strategy targeted economy of code and aimed to lower complexity.

Provide time in Public Date field

---

CHANGELOG.md
src/types/zodFlaw.ts

Add Flaw Affect component name validation

---

CHANGELOG.md
src/components/AffectedOfferingForm.vue
src/components/__tests__/AffectExpandableForm.spec.ts
src/stores/osimRuntime.ts

Add Errata Advisory link in Trackers to Errata Tool

Add Errata Tool for Tracker

---

src/components/AffectExpandableForm.vue
src/components/AffectedOfferingForm.vue
src/components/AffectedOfferings.vue
src/components/IssueFieldState.vue
src/components/__tests__/AffectExpandableForm.spec.ts
src/composables/useFlawAffectsModel.ts
src/constants/flawFields.ts
src/services/AffectService.ts
src/types/zodAffect.ts
src/types/zodFlaw.ts
src/types/zodShared.ts

This endpoint has not yet been implemented by OSIDB.

✨ Support bulk affect updates at independent affects endpoint

---

features/flaw_detail.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

Add test case for recover affect from deleting

---

CHANGELOG.md
src/components/FlawForm.vue
src/components/__tests__/FlawForm.spec.ts

Only allowed flaw sources listed in flaw edit page

Show Allowed Sources for Flaw Edit

---

CHANGELOG.md
src/components/IssueSearchAdvanced.vue
src/components/__tests__/FlawSearchView.spec.ts
src/constants/flawFields.ts

Add CVE Description Review field to advanced search

Add CVE Description Review field to advanced search

---

CHANGELOG.md
src/components/FlawForm.vue
src/components/__tests__/FlawForm.spec.ts

Only allowed flaw sources listed in flaw create page

Show Allowed Sources for Flaw Creation

---

CHANGELOG.md
src/components/AffectExpandableForm.vue
src/components/AffectedOfferingForm.vue
src/components/AffectedOfferings.vue
src/components/FlawForm.vue
src/components/IssueFieldEmbargo.vue
src/components/__tests__/AffectExpandableForm.spec.ts
src/components/widgets/LabelEditable.vue
src/composables/useFlawAffectsModel.ts
src/utils/__tests__/helpers.spec.ts
src/utils/helpers.ts
vite.config.ts

- Makes `deepCopyFromRaw` easier to understand
- Adds test coverage for deepCopyFromRaw
- Proactively fixes a bug with deepCopyFromRaw
- Changes `theAffects` in `useFlawAffectsModel` from being a ref of a ref, which was the source of the error

🐛 Reset affects when flaw is reset

---

.eslintrc.json
src/components/BootstrapLabelInputExample.vue
src/components/CvssCalculator.vue
src/components/Navbar.vue
src/components/widgets/EditableDate.vue
src/components/widgets/Toast.vue

- [-] Changelog not updated
- [-] Test cases not added/updated
- [-] No Jira ticket related
Update lint rules to improve maintainability of the code base.
- Throw error instead warn on non trailing commas (comma-dangle)
- Add rule to avoid using unnecessary `let` declarations (prefer-const)
- Correct existent lint issues for this changes on the code base
-

Task: Lint rules update

---

src/components/AffectedOfferingForm.vue
src/components/CvssCalculator.vue
src/composables/useFlawAffectsModel.ts
src/composables/useFlawCvssScores.ts
src/composables/useFlawModel.ts

🐛 Fix modification tracking in affects (again)

---

src/composables/useFlawsFetching.ts
src/composables/useSearchParams.ts
src/constants/flawFields.ts
src/views/FlawSearchView.vue

Update API request param for CVE_ID emptiness

OSIM: Implement advanced searching on emptiness for CVE ID

---

CHANGELOG.md
src/components/IssueSearchAdvanced.vue
src/components/__tests__/FlawSearchView.spec.ts
src/constants/flawFields.ts

[OSIDB-2892] [Advanced Search on the Incident State field]

Add Incident State for Advanced Search

---

build/nginx-default.d-osim.conf

add a glob allowing optional config file for nginx

---

features/flaw_detail_embargo.feature
features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

Fix failed cases for affects

---

features/flaw_detail_public.feature
features/pages/base.py
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

Add test case for filing tracker to jira with affectness is Affected

---

CHANGELOG.md

Updates the changelog for the last release [OSIM v2024.6.0](https://github.com/RedHatProductSecurity/osim/releases/tag/v2024.6.0)
- Change unrelased to release version
- Should we include this on the released tag?
- There is a bunch of items on "[Unreleased] (TODO update for 2024.1.1 and 2024.2.0 releases)" but I didn't find any of these tags. Not sure what to do with that, should be included in this release?

Changelog: Release v2024-6-0 update

---

CHANGELOG.md
src/services/AffectService.ts

Fix Flaw save with removing unsaved affects
Don't call OSIDB API Call to remove unsaved affects on flaw

Fix Flaw save with removing unsaved affects

---

CHANGELOG.md
src/components/CvssCalculator.vue
src/composables/useFlawCvssScores.ts
src/composables/useFlawModel.ts

Fix CVSS score value reset on flaw reset
Fix CVSS score value reset on flaw reset
[Screencast from 2024-06-17 15-35-06.webm](https://github.com/RedHatProductSecurity/osim/assets/156366006/1128e5e3-713d-40b3-8b43-383598f4112d)

OSIDB:2701 Fix CVSS score value reset on flaw reset

---

CHANGELOG.md
src/components/IssueSearchAdvanced.vue
src/components/__tests__/FlawSearchView.spec.ts
src/constants/flawFields.ts

Add affect status to advanced search

Add Affectedness on Advanced Search

---

CHANGELOG.md
src/components/FlawForm.vue
src/components/__tests__/FlawForm.spec.ts
src/components/__tests__/SampleData.ts
src/types/zodFlaw.ts

Add created timestamp to flaw detail page

Add Created Date on Flaw Edit

---

CHANGELOG.md
src/components/AffectedOfferings.vue
src/components/AffectsTrackers.vue
src/composables/useTrackers.ts

Improve manage trackers UI:
https://github.com/RedHatProductSecurity/osim/assets/17716232/391873e4-3ef1-4501-b9df-cfaaa0cec148
- Adjust spacing
- Remove unnecessary space and make responsive
- Indicate when trackers are being filed and disable File Trackers button when filing
- Define UI area more clearly
Closes OSIDB-2949

✨ Improve Manage Trackers UI

---

features/flaw_detail_public.feature
features/pages/base.py
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

add test cases for filing tracker to bz

---

CHANGELOG.md
src/types/zodFlaw.ts

Add Error for duplicated affects
[Screencast from 2024-06-26 14-25-55.webm](https://github.com/RedHatProductSecurity/osim/assets/156366006/220ef7bd-473b-4c36-a782-e0d9d388acf5)

Add Error for duplicated affects

---

.stylelintignore
package.json
vitest.config.ts
yarn.lock

✨ Provide test coverage reporting

---

CHANGELOG.md
src/components/AffectedOfferingForm.vue
src/components/widgets/EditableDate.vue
src/utils/helpers.ts

- ~~[ ] Test cases added/updated~~

✨ Format timestamps in tracker table

---

CHANGELOG.md
src/components/FlawFormOwner.vue
src/components/IssueQueue.vue
src/components/Navbar.vue
src/components/__tests__/FlawFormOwner.spec.ts
src/components/__tests__/IssueQueue.spec.ts
src/components/__tests__/Navbar.spec.ts
src/services/JiraService.ts
src/stores/UserStore.ts
src/stores/__tests__/SettingsStore.spec.ts
src/stores/__tests__/UserStore.spec.ts

This PR fixes Flaw Owner Self assign and filtering for My Issues on index page. Jira username is fetched on Login or when Jira token is correctly set.
* fetching Jira username from Jira as usernames in Jira have various formats (emails, kerberos names, etc.)
* storing Jira username in userStore
* using the correct Jira user name for Flaw Owner self assign and My Issues filter
n/a

Use correct Jira username for Flaw owner

---

features/constants.py
features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

Set up: export FLAW_ID=$CVE_id and the flaw has affect.

Add test case for filed trackers list

---

CHANGELOG.md
src/components/IssueQueue.vue
src/components/__tests__/IssueQueue.spec.ts

Exclude empty state from open issues filter
Closes OSIDB-3067

Exclude Empty State For Open Issues

---

features/flaw_detail_public.feature
features/pages/base.py
features/pages/flaw_detail_page.py
features/pages/home_page.py
features/steps/flaw_detail.py
features/steps/flaw_list.py

Add test case for contributors field

---

features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

Add testcase for file zstream tracker

---

CHANGELOG.md
src/components/FlawForm.vue

Sort Affects by Product Family
Closes OSIDB-2533

OSIDB-2533: Sort Affects by Product Family

---

CHANGELOG.md
src/components/FlawContributors.vue
src/components/FlawFormOwner.vue
src/components/__tests__/FlawContributors.spec.ts
src/components/__tests__/FlawFormOwner.spec.ts
src/components/widgets/DropDown.vue
src/components/widgets/EditableTextWithSuggestions.vue
src/components/widgets/LabelDiv.vue

Added a dropdown suggestion integrated with jira
Closes OSIDB-3004

OSIDB-3004: Add suggestions to flaw owner field

---

CHANGELOG.md
src/components/FlawComments.vue
src/components/__tests__/FlawComments.spec.ts
src/components/widgets/DropDown.vue
src/components/widgets/LabelTextarea.vue

Added suggestions for jira mentions on internal comments text area. Most of the code is to calculate cursor position for correct dropdown positioning. 
I Tried to isolate the code so it's easy to integrate with #285 once merged.
> Video in jira ticket for privacy reasons
I created this PR from #321 so this needs to be merge after that PR
Closes OSIDB-3005

OSIDB-3005: Add suggestions for jira mentions in internal comments

---

features/flaw_detail_embargo.feature
features/flaw_detail_public.feature
scripts/run_automation_test.sh

Update the autotest script to skip the affect cases

---

features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

add test case for CVSSv3 field

---

features/flaw_detail_public.feature
features/page_factory_utils.py
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

add test case for erase CVSSv3 field

---

CHANGELOG.md

📝 Update change log for release

---

src/components/CveRequestForm.vue
src/components/Login.vue
src/components/ToastContainer.vue
src/components/widgets/EditableText.vue
src/composables/service-helpers.ts
src/composables/useFlawAffectsModel.ts
src/composables/useFlawCommentsModel.ts
src/composables/useFlawModel.ts
src/composables/useFlawsFetching.ts
src/composables/useJiraContributors.ts
src/composables/useNetworkQueue.ts
src/composables/useTrackers.ts
src/router/index.ts
src/services/FlawService.ts
src/services/JiraService.ts
src/services/OsidbAuthService.ts
src/shims/console/index.js
src/stores/UserStore.ts
src/stores/osimRuntime.ts
src/views/FlawEditView.vue

-  ~Changelog updated~
-  ~Test cases added/updated~
Now that we have access to the logs on production it makes sense to provide some extra information on where the log was originated, so I used the format `fileName::functionName() [message]` for all the logs we have currently, this is not enforced, so we are free to integrate with other formats (or none) if needed.
I also changed some of the log messages to `debug` so they are excluded in production
Closes OSIDB-3270

OSIDB-3270: Refactor log messages

---

CHANGELOG.md
src/types/zodAffect.ts

Supports WONTFIX for corner cases.
See above.
Need for WONTFIX remains.

♻️ Allow WONTFIX affect resolution

---

features/flaw_detail_embargo.feature
features/flaw_detail_public.feature
features/pages/base.py
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

Fix failing test scenarios

---

package.json
src/components/IssueSearchAdvanced.vue
src/components/__tests__/FlawSearchView.spec.ts
src/components/__tests__/IssueSearchAdvanced.spec.ts
src/components/__tests__/__snapshots__/FlawSearchView.spec.ts.snap
src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap
src/scss/djangoql.scss
src/views/FlawSearchView.vue
yarn.lock

Integrate `djangoql-completion` library to add suggestions and auto completion in the advanced search query
>[!NOTE]
> This PR depends on #397 
Closes OSIDB-3340

OSIDB-3340: Suggestions on advanced search

---

features/flaw_detail_embargo.feature
features/flaw_detail_public.feature
features/pages/advanced_search_page.py
features/pages/base.py
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

Update add affect automation test case for affect redesign

---

src/components/IssueSearchAdvanced.vue
src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap

- [-] Jira ticket updated
Remove unsupported sorting field `mitigation`
Remove unsupported sorting field `mitigation`

🐛 Remove unsupported mitigation ordering field

---

features/common_utils.py
features/flaw_detail_embargo.feature
features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py
features/steps/flaw_list.py
features/utils.py

add test case: update affect

---

features/flaw_detail_public.feature
features/pages/base.py
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

add case:Bulk update affects

---

features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

add case:Customize affects pagination number

---

package.json
src/components/__tests__/__snapshots__/FlawFormOwner.spec.ts.snap
vitest.config.ts
yarn.lock

Enable code coverage reports on CI with configured minimum thresholds 
Closes OSIDB-3423

OSIDB-3423: Enable coverage on CI

---

features/advance_search.feature
features/pages/advanced_search_page.py
features/pages/home_page.py
features/steps/advance_search.py
features/steps/flaw_list.py
features/utils.py

add case for advance search: Sort search result by sortable fields in result table

---

CHANGELOG.md
src/components/FlawForm.vue
src/components/FlawHistory.vue
src/components/__tests__/FlawHistory.spec.ts
src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap
src/components/__tests__/__snapshots__/FlawHistory.spec.ts.snap
src/components/widgets/LabelCollapsible.vue

Optimizes the display of history section, for cases where it is highly populated, by adding a pagination feature.
- Implements pagination logic on the history section using reusable composable
- Updates UI to properly display pagination control
https://github.com/user-attachments/assets/22b24b3d-0a5f-4222-a9ee-11c0c936c8ca
Closes OSIDB-3563

✨ OSIDB-3563: History pagination

---

features/README.md
features/common_utils.py
features/constants.py
features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py
features/utils.py

add integration test: File trackers for individual affect

---

features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

add integration test case: File trackers for selected affects in a flaw

---

CHANGELOG.md

* Support multiple user saved searches (`OSIDB-3554`)
* Allow editing/removing/adding saved user searches (`OSIDB-3555`)
* Added pagination to history section (`OSIDB-3563`)
* Integrate CVSS Calculator on affect's CVSS editing field (`OSIDB-3434`)
* Time format on history dates changed from 12h to 24h (`OSIDB-3645`)
* Fix some update streams not showing until De/Select All button is clicked on PS Modules with *some but not all* trackers already filed (`OSIDB-3674`)
* Prevent flaw saving if CVSS vector is invalid (`OSIDB-3275`)
* Unable to remove affect CVSS (`OSIDB-3675`)
* Extend advance search UI to handle multiple saved searches (`OSIDB-3556`)

📝 Release 2024.11.1

---

features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

add intgration test case: Select/Deselect all trackers in tracker manager

---

CHANGELOG.md

📝 Remove duplicated items

---

features/advance_search.feature
features/pages/advanced_search_page.py
features/pages/flaw_detail_page.py
features/steps/advance_search.py
features/steps/common_steps.py
features/steps/flaw_create.py
features/steps/flaw_detail.py
features/utils.py

integration test: Sort search result by extended sortable field

---

features/flaw_detail_public.feature
features/pages/flaw_detail_page.py
features/steps/flaw_detail.py

integration test:Filter trackers by Status field

---

CHANGELOG.md
src/components/FlawHistory/FlawHistory.vue
src/components/__tests__/FlawHistory.spec.ts
src/components/__tests__/__snapshots__/FlawHistory.spec.ts.snap
src/utils/helpers.ts

Provide seconds in flaw history timestamps
Closes OSIDB-3958

✨ Provide seconds in flaw history timestamps

---

CHANGELOG.md
src/components/IssueQueue/IssueQueueItem.vue
src/components/__tests__/__snapshots__/IssueQueue.spec.ts.snap

Adds colors to flaw labels in the list view.
- Add functions for color logic
- Changes the style of the labels element
- Updates the snapshot
- Adds missing changelog entry for the justifications hot fix (v2025.3.1)
Closes OSIDB-3992

✨ Dynamic label colors

---

CHANGELOG.md
src/components/IssueQueue/IssueQueueItem.vue
src/components/__tests__/__snapshots__/IssueQueue.spec.ts.snap

Remove capitalization of labels on flaw queue view so they are displayed as the exact value set in OSIDB.
- Remove capitalization class from labels on flaw queue
- Update snapshots
- Labels on table are already being displayed as the value in OSIDB
Closes OSIDB-3994

💄 Remove labels capitalization

---

Dockerfile

Pinned the base image to the latest available to fix some security issues
Closes OSIDB-4230

[OSIDB-4230] Update base image

---

src/App.vue
src/components/Settings/Settings.vue
src/router/index.ts
src/services/ApiKeyService.ts
src/services/OsidbAuthService.ts
src/stores/SettingsStore.ts
src/stores/UserStore.ts

Hotfix for realease v2025.7.0:
I applied wrong stash and all changes from @MrMarble  suggestions on PR https://github.com/RedHatProductSecurity/osim/pull/585 were missing on the merge. This PR attempts to address those missing changes.

🐛 Fix missing review changes

---

build/entrypoint.d/20-osim-runtime-json.sh

Proof of concept of the possible implementation of feature flag discussed in #617 
This should export every environment variable exposed to the container with the prefix `OSIM_FLAG_`. The prefix is removed, and transformed to camelCase before adding it to `runtime.json`.
For example, given these environment variables:
```env
OSIM_FLAG_CWE_AI_SUGGESTIONS=true
OSIM_FLAG_CVSS_V4=false
OSIM_FLAG_DEFAULT_CVSS_VERSION="V3"
```
Generates this runtime.json:
```jsonc
{
"featureFlags": {"cvssV4": false,"cweAiSuggestions": true,"defaultCvssVersion": "V3"},
// other keys in runtime...
}
```
Updating this variables in OpenShift and/or ops repository *and* restarting OSIM (so the `runtime.json` is regenerated) should be the only thing needed when updating the feature flags

Automatic flag expansion from environment

---

CHANGELOG.md
src/components/__tests__/FlawForm.spec.ts
src/types/zodFlaw.ts

…d description
Removes validation.
Closes OSIDB-4441

👔 Remove validation preventing incident state changes without approved description

---

src/widgets/DebouncedInput/DebouncedInput.vue
src/widgets/DebouncedInput/__tests__/DebouncedInput.spec.ts

Created a bare input widget that supports debouncing
Closes OSIDB-4471

[OSIDB-4471] Create `DebouncedInput` widget
