src/components/Settings.vue, src/components/ToastContainer.vue, src/components/__tests__/Settings.spec.ts, src/services/ApiKeyService.ts, src/services/OsidbAuthService.ts, src/stores/SettingsStore.ts, src/stores/ToastStore.ts, src/stores/__tests__/SettingsStore.spec.ts, vitest.config.ts
- Reworks missing API key notification interface to accommodate multiple missing API keys (JIRA and BZ)
> <img src="https://github.com/RedHatProductSecurity/osim/assets/17716232/66f1b35a-4f44-4573-8a3f-eaffb711f854" width="300px">
- Provides field in settings for ephemeral storage of JIRA API key, analogous to BZ KEY field (not persisted)
- Sets request header [specified in `osidb/openapi.yml` for JIRA api key](https://github.com/RedHatProductSecurity/osidb/blob/dc48ee1597f33633fe751a06a43f47bc67ca7eaf/openapi.yml#L3440-L3450)
- Provide test coverage for `<Settings/>` and its pinia store `SettingStore`
=> Support JIRA API Key in session settings

src/types/zodFlaw.ts
`owner` was missing from the schema used by the form, but no longer.
=> Fix bug where owner was not able to be updated by Flaw Edit Form

src/components/IssueEdit.vue, src/components/__tests__/IssueEdit.spec.ts, src/types/zodFlaw.ts
* Provides an editable field for assigning team id
* Bundles in tooltips (optional, can be removed)
=> Add Team Id to Issue Edit (Unblocks QE testing for Flaw Status Workflow)

src/components/IssueQueue.vue
MyIssues filter fix on IndexView
After user login, MyIssues filter is passing 'Current_user' filter to owner query. This is happening because of losing reactivity on username.
=> Fix MyIssues filter on IndexView

Dockerfile, build/entrypoint.d/40-setup-logging.sh
This PR makes logs available in Splunk when deployed to MP+.
In order to achieve that, this PR uses OSIM_ENV variable to define if logs should be redirected to `stdout` or if they should be in `/var/log/nginx`.
Closes OSIDB-2339.
=> setup nginx logs for splunk

CHANGELOG.md, src/components/AffectedOfferings.vue, src/components/FlawComments.vue, src/components/FlawForm.vue, src/components/IssueFieldAcknowledgments.vue, src/components/IssueFieldReferences.vue, src/components/widgets/EditableList.vue, src/components/widgets/LabelCollapsable.vue, src/components/widgets/LabelStatic.vue, src/components/widgets/LabelTextarea.vue
Implements **OSIDB-2313** and applies changes based on stakeholder feedback:
- New layout on Descriptions, References and acknowledgements
- Renames `Description` (Comment#0) and `Summary` based on OSIDB API logic
- Makes "description" text area fields visible with empty content (hidden/shown after saving flaw)
- Adds optional behavior control on `LabelCollapsable` when passing `isExpandable` property
- Modifies `EditableList` to use new `isExpandable` property of `LabelCollapsable`
- Disables `EditableList` collapse button if no items to list
- Shows number of items on `EditableList` label
- Rises the spacing between `FlawForm` sections
- Fixes overlapping on edit buttons of `EditableList` items
- Other minor style adjustments
=> Task/OSIDB-2313 FlawForm Modifications

src/components/FlawForm.vue, src/components/__tests__/FlawForm.spec.ts
It removes the trackers section from the FlawForm when it is on CREATE mode only.
Implements https://issues.redhat.com/browse/OSIDB-2321
=> OSIDB-2321: Removed trackers from create flaw form and added the unit tests too

CHANGELOG.md, src/components/FlawForm.vue, src/composables/useCvssScoresModel.ts
This PR:
* makes variables in CVSS composable more explicit (eg. versions, issuers)
* fixes cvss data search - version and issuer need to be both specified as with only issuer specified it might happen that CVSSv2 score was found first and used
Consideration:
CVSS composable should probably be redesigned a little bit a generalized in the future as there will be CVSSv4 as well
This partially solves OSIDB-2308 (sub-task OSIDB-2389)
=> OSIDB-2308: Fix CVSS composable

CHANGELOG.md, src/components/FlawForm.vue, src/components/IssueFieldEmbargo.vue, src/components/IssueQueue.vue, src/components/Navbar.vue, src/composables/useFlawModel.ts, src/router/index.ts, src/services/ApiKeyService.ts, src/types/zodFlaw.ts, src/utils/helpers.ts
- CVE validation on OSIM now matches OSIDB
- New error messages
- CVEs can be blank (OSIDB seems to complain for me still though)
- Reported Date validation has been added (doesn't show on initial load for Create Flaw for some reason)
- Comment#0 minimum length is back to one from 1
Handles:
- OSIDB-2260
- OSIDB-2453
- OSIDB-2311
Changes comment#0 error messages to indicate `Comment#0` instead of `description` and remove arbitrary 10 character length.
=> Revises Flaw validations

src/components/AffectedOfferingForm.vue, src/composables/useFlawAffectsModel.ts, src/types/zodFlaw.ts
* Fixes not sending resolution along with delegated_resolution
Includes `resolution` along with `delegated_resolution`, where `resolution` was erroneously removed
=> 🐛 Fix affects not being created with certain data

CHANGELOG.md, src/components/IssueFieldReferences.vue, src/types/zodFlaw.ts
Fix for incorrect prompt message and title on reference deletion popup:
> Are you sure you want to delete this acknowledgment? This action will take place immediately and will not require saving the Flaw to take effect.  
- Replaced "Acknowledgment" mentions for "Reference" on `IssueFieldReferences` modal texts
- Corrected minor lint `max-len` warn on `zodFlaw.ts` cve_id validation message
=> 🐛 OSIDB-2458 Reference deletion wrong message

src/components/IssueQueue.vue, src/components/IssueQueueItem.vue, src/services/FlawService.ts
Index/Flaw list view uses `flaw.state` instead of `flaw.classification.state`; this has been remedied.
Issue Queue item component remaps to the correct field for workflow status.
Very ambiguously named field name difference--should one (`flaw.state`) be deprecated/removed in OSIDB?
=> 🐛 Source flaw workflow status from classification field on flaw list [OSIDB-2504]

src/components/AffectedOfferings.vue
Bug when changing an affect (step 2 of bug reproduction steps) would cause the affect section to break, affecting the form and expandable menu functionalities.
Fixes the collapsible state management.
=> 🐛 Fix collapsible state management for affected product streams

Dockerfile, build/entrypoint.d/40-setup-logging.sh
/etc/nginx/nginx.conf is owned by root, but the entrypoint runs as the user, so the entrypoint script can't set the log paths.
Fix it by using symlink indirection.
=> Fix log file permissions in container

CHANGELOG.md, src/components/IssueQueue.vue, src/components/__tests__/IssueSearchAdvanced.spec.ts, src/constants/flawFields.ts, src/views/FlawEditView.vue
Fix Advanced Search has 2 listings for 'Affect Update Stream'
Fix Advanced Search has 2 listings for 'Affect Update Stream'
Fix 'See all flaws' link on flaw not found page
Fix Scrollbar on IssuesQueue (only show when it's necessary)
=> Fix AdvanchedSearch dropdown option and all flaws link

CHANGELOG.md, src/components/IssueFieldReferences.vue
Shows the references link as an url instead of having the link on the timestamp.
Timestamp is kept as an independent field for info purposes.
- Shows url on references links
- Changes the layout on info fields at references
- Improves the contrast ratio on "External" badges text
- The layout change to vertical (of badge - timestamp - url)  was considered as some urls can be quite long so they should have space inline
=> 💄 OSIDB-2512: Show url on references links

CHANGELOG.md, src/components/FlawForm.vue, src/components/IssueQueue.vue, src/components/IssueQueueItem.vue, src/components/IssueSearchAdvanced.vue, src/components/__tests__/FlawForm.spec.ts
Temporary hiding the `Source` column on Flaw queues and renaming `Source` field labels to `CVE Source`:
> The current value of the source field is where the flaw was reported. This information is not very valuable on this page. Instead, we need to track what system the flaw was created in (SNOW, Assembler, etc; ). Today, we only get flaws from assembler or a direct users. So we should hide the source column on Index page for now. When we do an integration with SNOW, we could then expose the field with more meaningful data.
> Additionally, we should rename the source field on the CVE page to 'CVE Source' so that it is more clear what the field represents. 
- Hidden `Source` column from `IssueQueue` and `IssueQueueItem`
- Renamed `Source` field label to `CVE Source` at `FlawForm`
- Renamed …
=> 🩹 OSIDB-2562 Hide source column

CHANGELOG.md, src/components/IssueQueue.vue, src/components/IssueSearchAdvanced.vue, src/components/__tests__/App.spec.ts, src/components/__tests__/FlawSearchView.spec.ts, src/components/__tests__/IndexView.spec.ts, src/components/__tests__/IssueQueue.spec.ts, src/components/__tests__/IssueSearchAdvanced.spec.ts, src/stores/SearchStore.ts, src/stores/__tests__/SearchStore.spec.ts, src/views/FlawSearchView.vue, src/views/IndexView.vue
Add default filters on Index Page
- Add Save Default filter button on AdvancedSearch Page
- Show default filter checkbox on IndexView Page
- Hide default filter checkbox when default filter is empty
- Do we need to show default filters always when filter is empty?
- Default Filter reset functionality
[Screencast from 2024-05-01 19-39-55.webm](https://github.com/RedHatProductSecurity/osim/assets/156366006/8507c675-4467-456d-9e49-4819dd5c9182)
=> OSIDB-2055: Add Default Filter on Index Page

CHANGELOG.md, src/components/CvssCalculator.vue, src/components/FlawForm.vue, src/components/__tests__/CvssCalculator.spec.ts, src/components/__tests__/FlawForm.spec.ts, src/components/widgets/LabelStatic.vue, src/composables/useCvssCalculator.ts
Implements Cvss calculator, using Cvss v3.1 [specification](https://www.first.org/cvss/v3.1/specification-document),
as an embedded component on `FlawForm` and main controller for `Cvss3 Vector` and `Cvss3 Score` fields.
**Features**:
- Dynamic collapsible behavior based on Cvss3 vector input focus
- Compact calculator style inspired by [cvss.js.org](https://cvss.js.org/)
- Dynamic colors on Cvss3 factors based on severity
- Validation for incomplete Cvss3 vector
- Erase button to cleanup values on Cvss3 vector and score
- Factor tooltips with description of each factor value
- Handles pasting in CVSS scores: vector order does not matter! s/o to @C-Valen for his implementation which supports this (added by @superbuggy) 
- Highlights sections of CVSS when editing (added by @superbuggy)
- …
=> ✨ OSIDB-1204 Create CVSSv3 calculator

CHANGELOG.md, src/components/FlawForm.vue, src/components/IssueFieldEmbargo.vue, src/composables/useFlawModel.ts, src/views/FlawEditView.vue
Refactor of unembargo workflow to make the confirmation pop up shown on save flaw.
- Fixed stuck saving state on flaw update/creation (restore `isSaving` variable before return)
- Added a `isValid` method on `useFlawModel` that returns the boolean result of the flaw validation
- Refactored `IssueFieldEmbargo` for the "onSave" confirmation
- Added control of unembargo modal on `FlawForm` 
- Added reset button on embargo field (visible only if going to be unembargoed)
- Added warning tooltip on embargo field (only if going to be unembargoed)
- Other minor style improvements on `IssueFieldEmbargo`
- Removed unused `committedFlaw` var at `FlawEditView
- `isValid` method purpose is to be able to check the result of the flaw validation without any UI information. For this specific case it was …
=> ♻️ OSIDB 1596: Unembargo confirmation on save flaw

src/components/FlawForm.vue, src/components/IssueFieldState.vue, src/components/__tests__/FlawForm.spec.ts
Well, we changed that dang ol field name.
Flaw `Status` was renamed to `State` to be consistent with Flaw index column `State`.
The children. and also everyone else.
=> 💬 Rename Flaw Status to State to be consistent with Flaw index

CHANGELOG.md, src/components/FlawForm.vue, src/components/FlawFormAssignee.vue, src/components/__tests__/FlawForm.spec.ts, src/components/__tests__/FlawFormAssignee.spec.ts, src/components/widgets/EditableText.vue, src/components/widgets/LabelEditable.vue
Well then just go on ahead there and click on that there pencil button and wontcha know it, there's a big old bright shiny red button that reads "Self-Assign" that pops up--go on now, go ahead and give 'at dang ol thing a click now. Ok then.
https://github.com/RedHatProductSecurity/osim/assets/17716232/bcef1418-53f5-4b2d-bc0b-be0a3db62106
Well I'll be danged, there's a button there now.
Everyone's wrist RSIs. Kept the layout consistent.
=> ✨ Support self-assigning flaws

src/components/CvssCalculator.vue, src/composables/useCvssCalculator.ts
Cleanups small parts of obsolete code related to CvssCalculator.
- Removes deprecated `getFactorColor` code
- Removes obsolete console log
The `getFactorColor` method from `useCvssCalculator` was substituted with @superbuggy's hue approach.
The console log was used for debugging, not required anymore.
=> Task: Minor calculator code cleanup

CHANGELOG.md, src/composables/useCvssScoresModel.ts, src/composables/useFlawModel.ts, src/services/FlawService.ts
CVSS scores are now saved after flaw creation by interacting with the dedicated endpoint.
- Adds additional request after flaw creation to save CVSS scores.
- Grabs flaw UUID after creation.
=> 🐛 Save CVSS on Flaw Creation

CHANGELOG.md, src/components/FlawForm.vue, src/components/widgets/EditableList.vue, src/composables/useFlawAttributionsModel.ts, src/composables/useFlawModel.ts
Fix some bugs in attributions section, remove unused code and implements form disabling on attributions save actions.
- Removes unused code on `FlawForm`
- Fix attributions reactivity loss by adding a watcher to the model `useAttributionsModel`
- Fix modal index issues on `EditableList` by making it a computed property
- Add a cleanup of modified items array after save actions on `EditableList`
- Implements the form disabled state for attributions saving actions
`flawReferences` and `flawAcknowledgments` were not being updated after performing the `flaw:refresh`, the reactivity was being lost the way they are implemented, making the next actions on the attributions form inconsistent. 
I added a watcher cause it looked to me the simpler working solution for this, however I think we could …
=> Fix: Attributions form bugs

src/services/FlawService.ts, src/utils/helpers.ts
This PR aims to address an issue found by @JakubFrejlach where OSIM was sending the `updated_dt` of the flaw, to sub-models (i.e. Acks, Refs, Comments, Affects, etc.), making OSIDB respond with 409 Error "Save operation based on an outdated model instance".
- Renamed `getFlawUpdatedDt` function to `getUpdatedDt` on `FlawService.ts`
- Use the `options.url` on `beforeFetch` to get the specific object `update_dt`
- Removed potentially deprecated
- This issue was only manifested when OSIDB's BZ Sync was disconnected, in other case the the updated_dt was not compared from OSIDB data but BZ.
- @superbuggy I removed some code that looked deprecated after this changes. Would you mind to have a look on that to ensure nothing essential was removed?
=> Fix: Use object-specific updated_dt

build/entrypoint.d/20-osim-runtime-json.sh
Adds OSIM_BACKENDS_ERRATA into entrypoint script.
Add errata url into runtime.json through entrypoint script.
=> add OSIM_BACKENDS_ERRATA into entrypoint script

CHANGELOG.md, src/components/FlawForm.vue, src/components/__tests__/FlawForm.spec.ts
Can not remove Description, Statement, Mitigation
=> 🐛 Fix Remove Summary, Statement, Mitigation Button on FlawForm

CHANGELOG.md, src/components/FlawForm.vue, src/components/__tests__/FlawForm.spec.ts, src/components/widgets/EditableDate.vue, src/components/widgets/EditableText.vue, src/components/widgets/LabelEditable.vue, src/components/widgets/LabelTextarea.vue, src/types/zodFlaw.ts
Restores display of required field validation results.
Explicitly passing in errors to `EditableDate` and `EditableText` components.
Broke when only passing `$attrs.class` instead of `$attrs`. May be good to avoid reliance on passing props via `$attrs`
=> 🐛 Restore required field validations

CHANGELOG.md, src/components/FlawForm.vue, src/composables/service-helpers.ts, src/composables/useFlawModel.ts
- [-] no tests added 
Flaw creation did not recover from errors while saving. It does now.
- Added saving animation
- Recover from save failures
The user's finite patience.
=> 🐛 Recover from save errors during flaw creation, show saving animation

CHANGELOG.md, src/components/AffectedOfferings.vue, src/composables/useFlawAffectsModel.ts
* Add deep equality check to prevent unintentionally tracking affects as modified.
Affects were being tracked as modified when they weren't, this fixes that issue.
Added a deep equality check to properly check for modified affects.
Affects began triggering the watcher when loaded, which marked them as modified erroneously as soon as they loaded.
=> 🐛 Don't save unmodified affects

src/components/AffectedOfferingForm.vue, src/components/__tests__/AffectExpandableForm.spec.ts, src/components/__tests__/FlawForm.spec.ts, src/composables/useFlawAffectsModel.ts, src/types/zodAffect.ts
Remove `type` field from `Affect` type
`Affect.type` only has one possible value `DEFAULT` and for that was removed from OSIDB in OSIDB-2743
Openapi client should be re-generated once OSIDB 4.0 is released
=> OSIDB-2780: Remove affect type

features/advance_search.feature, src/components/FlawForm.vue, src/components/IssueSearchAdvanced.vue, src/components/__tests__/FlawForm.spec.ts, src/composables/useFlawModel.ts, src/services/FlawService.ts, src/types/zodFlaw.ts
Remove `type` field from `Flaw` type
`Flaw.type` only had one used value `VULNERABILITY` and for that was removed from OSIDB in OSIDB-2735
Openapi client should be re-generated once OSIDB 4.0 is released
=> OSIDB-2773: Remove flaw type

CHANGELOG.md, src/components/__tests__/FlawForm.spec.ts, src/services/FlawService.ts, src/services/TrackerService.ts
Apparently OSIM already does use the new `major_incident_state` and thus this whole PR is just about removing the old field.
Any remaining usage of the `is_major_incident` field has been removed
n/a
=> Remove is_major_incident field usage

features/flaw_filter.feature, features/steps/flaw_filter.py, src/services/FlawService.ts
`Flaw.state` (not to confuse with `Flaw.classification.state`) is deprecated and OSIDB is going to remove it as per https://github.com/RedHatProductSecurity/osidb/pull/543. OSIM should make sure to not to use it.
Removed `Flaw.state` usage from the special keyword search as well as not asking for the field in `include_fields` param of `FlawService` since this field is not longer provided by OSIDB
OpenApi client should be generated once OSIDB 4.0 is  released
=> OSIDB-2774: Remove flaw state field

CHANGELOG.md, features/advance_search.feature, src/components/AffectedOfferingForm.vue, src/components/FlawForm.vue, src/components/IssueSearchAdvanced.vue, src/components/__tests__/AffectExpandableForm.spec.ts, src/components/__tests__/FlawForm.spec.ts, src/composables/useFlawAffectsModel.ts, src/composables/useFlawModel.ts, src/services/AffectService.ts, src/services/FlawService.ts, src/types/zodAffect.ts, src/types/zodFlaw.ts
Fixes a bug where cvss scores couldn't be saved when editing existent flaws.
This was causes by attempting to 
- Removes `beforeFetch` action on `postFlawCvssScores` as if there is no cvss scores (first cvss score creation) fetch would fail.
- [Edit] Removes `beforeFetch` action on `postFlawAcknowledgment` and `postFlawReference`
- [Edit] Removes `beforeFetch` action on `postAffectCvssScore`
- `beforeFetch` gets the `updated_dt` from the object to be updated, so it shouldn't be used when the object is being created for first time (e.g. Flaw Creations) cause there won't be any `updated_dt` to get from OSIDB side and action would fail.
=> Fix: Unable to save new cvss scores

CHANGELOG.md, src/components/FlawForm.vue, src/components/IssueFieldAcknowledgments.vue, src/components/IssueFieldReferences.vue, src/components/widgets/EditableList.vue, src/composables/useFlawAttributionsModel.ts, src/composables/useFlawModel.ts, src/services/FlawService.ts, src/stores/DraftFlawStore.ts
Add support for references and acknowledgements on flaw creation, fix minor bugs, add draft flaw state.
- Hide save refs/acks button on flaw creation form
- Handle saving refs/acks on flaw creation if present
- Create a store to handle draft flaw data when it is not saved correctly (mainly for concatenated service operations)
- Use the draftFlaw store to keep non saved attributions on the form (as draft)
- Fix some stuck states scenarios on saving flaw/attributions unsuccessfully
- Fix wrong updated_dt initialization on blank attributions
- Fix a bug where updated_dt is fetched for attributions creation
- References and ackowledgements are saved on flaw creation within the full form submit button
- Flaw is created first, uuid is taken from response and used in the refs/acks to save 
- …
=> Feat: Support references and acknowledgements on flaw creation

CHANGELOG.md, src/components/FlawComments.vue, src/components/__tests__/FlawForm.spec.ts, src/services/FlawService.ts, src/types/zodFlaw.ts
Flaw `Comment.type` is a single value enum (`BUGZILLA`) and will be removed in OSIDB as per https://github.com/RedHatProductSecurity/osidb/pull/552. OSIM should make sure not to use it.
Removed `type` field from the `ZodFlawCommentSchema` as well as the `FlawService`.
Talked with @JakubFrejlach about the link that pointed to `#${comment.type}/${comment.external_system_id}` and decided to remove the whole link since it had no use
OpenApi client should be re-generated once the **OSIDB 4.0** release comes out
=> OSIDB-2781: Remove comment.type field usage

CHANGELOG.md, src/components/AffectedOfferingForm.vue, src/components/FlawForm.vue, src/components/__tests__/AffectExpandableForm.spec.ts, src/composables/useFlawModel.ts, src/services/TrackerService.ts
Implements external links on trackers.
- Added a `trackerUrl` function on `TrackerService`
- Modified `trackerUuids` function  to provide `type` and `external_id`
- Renamed `trackerUuids` function to  `trackersDisplay`
- Used all above to implement trackers links on Affects and Flaw form
-
=> Feature: Tracker's external links

CHANGELOG.md, src/components/AffectedOfferings.vue
Adds a new button that conditionally renders to allow the users expand all affect modules
- Adds`areAllModulesCollapsed` computed property on `AffectedOfferings`.
- Adds `expandAll` function on `AffectedOfferings`.
- Adds a `Expand All` new button  on the affects section
- Was confirmed that only Modules (and not component details) should be expanded
- Credits to @superbuggy as this PR is just a rework from 'CollapseAll' functionality
=> Feature: Button to expand all affects

CHANGELOG.md, src/components/CveRequestForm.vue, src/components/FlawComments.vue, src/composables/useFlawModel.ts, src/services/FlawService.ts, src/types/zodFlaw.ts
OSIDB has changed the comments fields to be independent from BZ, i.e. meta_attr comment fields (`text`, `creator` and `is_private`) are now moved into the comment model.
This PR address the corresponding modifications on OSIM for those API changes.
Additionally both OSIDB and OSIM changes address the bug of comments not being  correctly displayed on instances that are disconnected from BZ (i.e. Local & UAT).
- Update `ZodFlawCommentSchema` for OSIDB API changes
- Update `FlawComments` component to use new model fields
- Add creator as parameter on `postFlawPublicComment`
- Remove deprecated code
- Changed format on comments datetime
- Removes link to source on comments datetime
- Link to comment source will be added in the incoming redesign PR
=> Task: Remap comments based on OSIDB changes

CHANGELOG.md, features/quick_search.feature, src/components/CvssNISTForm.vue, src/components/FlawForm.vue, src/components/__tests__/CvssNISTForm.spec.ts, src/components/__tests__/FlawForm.spec.ts, src/components/__tests__/SampleData.ts, src/composables/useFlawModel.ts, src/services/FlawService.ts, src/types/zodFlaw.ts
We are already showing `Flaw.description` as `Comment#0` field. This PR is a final step to ditch `Flaw.description` usage completely and start using `Flaw.comment_zero` which will be introduced in the OSIDB 4.0.0
* complete transition to `Flaw.comment_zero` usage
* minor - changed `flawSummary` prop to `summary` in CVSS NIST Form for less ambiguity.
This PR needs to be merged only after OSIDB-2740 is addressed!
=> Change description to comment zero

src/composables/useFlawModel.ts, src/types/zodFlaw.ts
When creating a new flaw, the default value `[""]` added an empty FlawComponent on form mount.
Fixed it by changing the value to `[]` and moving the validation from zod type to refine
|Before|After|
|---|---|
|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/3e9f31ec-5b6b-4d3d-8373-0c6e9473a161)|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/de3eb2c0-836a-4ae3-91f8-3abd0e681cc8)|
=> Fix: Use empty array as default

CHANGELOG.md, features/pages/flaw_detail_page.py, features/steps/flaw_detail.py, features/steps/flaw_filter.py, src/components/FlawForm.vue, src/components/FlawFormOwner.vue, src/components/__tests__/FlawForm.spec.ts, src/components/__tests__/FlawFormAssignee.spec.ts
Field is called `owner` in the API and the advanced search, so it should be called `Owner` in the details page as well
|Before|After|
|---|---|
|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/9a7d1b90-93dd-4c92-8bca-b56dfac8baf2)|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/e93636f8-c12e-43b9-a23e-f6d29a0ada03)|
Closes OSIDB-2898
=> OSIDB-2898: Rename assignee to owner in flaw detail pages

src/components/FlawForm.vue
- [-] No changelog updated
Fix the bug where unembargo button was not appearing on flaw form of embargoed flaws.
The problem was that removing the ref on `initialFlaw` made the `isEmbargo` not being reactive, so the embargoed component was reviving undefined for that `isEmbargoed` property.
- Make isEmbargoed a ref and edit the values every time `initialFlaw` changes
- Remove non required `reactive` on `initialFlaw` as it is nor reactive anymore
- isEmbargoed need to be reactive as it is required to make the embargoed field changing after the flaw refresh
=> Fix OSIDB-2904: Unembargoed btn not shown

CHANGELOG.md, src/components/FlawAlert.vue, src/components/FlawAlertsSection.vue, src/components/__tests__/AffectedOfferings.spec.ts, src/components/__tests__/CveRequestForm.spec.ts, src/components/widgets/OsimButton.vue, src/composables/useFlawAffectsModel.ts, src/composables/useFlawModel.ts, src/services/AffectService.ts, src/services/FlawService.ts, src/services/OsidbAuthService.ts, src/stores/osimRuntime.ts
Allows affects to be created and deleted with a single request, using the new `POST affects/bulk` and `DELETE affects/bulk` endpoints in OSIDB.
- No longer uses `POST affects` and `DELETE affects` endpoints in OSIDB.
Depends on #243, includes #264
=> ✨ Update and delete affects with single requests, in bulk

CHANGELOG.md, src/components/FlawForm.vue, src/components/__tests__/FlawForm.spec.ts
Added a link to the bugzilla bug if the id exists
=> OSIDB-2897: Add bugzilla flaw link

CHANGELOG.md, src/components/FlawForm.vue, src/components/__tests__/FlawForm.spec.ts, src/components/widgets/EditableDate.vue, src/composables/useFlawModel.ts
Changed the embargo  component to listen to model updates and added a callback to set the current datetime when unembargoing
Requires the changes in #271
=> OSIDB-2829: Auto set the public date when unembargo a flaw

CHANGELOG.md, src/components/IssueQueue.vue, src/components/IssueSearchAdvanced.vue
In advanced searching we call it "flaw status", in the api we call it "state" and in the detail page we call it "state". So we should update the advanced search field to call it "State".
|Before|After|
|---|---|
|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/4a3d642f-6e23-459b-8659-1a8ac5dba5f5)|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/15f51fc0-77e2-4681-a7c7-c0059e58da9a)|
Closes OSIDB-2899
=> OSIDB-2899: Rename Flaw Status to Flaw State in Advanced search

src/composables/useFlawCvssScores.ts
- ~~Test cases added/updated~~
Send `''` instead of `null` value for key `comment` of CVSS score POST request body.
It makes OSIDB sad (it triggers validations that reject the parsed CVSS score POST request body) when you send `null` and it's apparently annoying to change on the OSIDB end, if I understand correctly.
=> 👽 Use empty string for unimplemented CVSS comment field

CHANGELOG.md, src/components/CvssExlplainForm.vue, src/components/FlawForm.vue, src/components/__tests__/CvssExplainForm.spec.ts, src/components/__tests__/FlawForm.spec.ts, src/composables/useFlawCvssScores.ts
The old tooling allowed the engineers to explain the differences between RH and NIST CVSS score. 
This adds a form input to show/edit the comment
|Before|After|
|---|---|
|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/0edcc5cb-3992-4994-bd3a-a1771a084a03)|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/d0a4e4d9-9f8c-4f05-a20f-af798a7cd926)|
=> OSIDB-2913: CVSSv3 Score explanation

CHANGELOG.md, src/components/widgets/EditableDate.vue
Adds UTC to the public date field so users have clear what timezone is being used when either setting or reading that field.
- Adds UTC on EditableDate component for editing and displaying
=> Task OSIDB-2790: Use timezone on public date

CHANGELOG.md, src/components/AffectedOfferings.vue
- ~~Test cases added/updated~~
- Within the Affected Offerings accordion UI, when deleting a component, the module would collapse when there were no other expanded components, even if the Module Accordion UI was expanded. 
The Module Accordion UI will no longer collapses deleting a component when no other components in that expanded Module are expanded
=> ✨ Improve collapsing logic in Affected Offerings

CHANGELOG.md, src/components/CveRequestForm.vue, src/components/FlawComments.vue, src/components/FlawForm.vue, src/components/__tests__/FlawComments.spec.ts, src/components/widgets/Tabs.vue, src/composables/useFlawModel.ts, src/composables/useInternalComments.ts, src/services/FlawService.ts
Adds support for private comments on Bugzilla.
- Provides Private comment enum type
- Fix osidb comment filters
- Adapt service functions to handle private comments
- Update comment badges to include new private comment style
- Adds tooltips on comment tabs to clarify to the users each comment type scope
- Fix edge case where Jira request was being performed on flaws without task_key
- Adapt & extend comments test suite
- There is a PR coming to simplify all comments stuff into a single `FlawCommentsModel`
https://github.com/RedHatProductSecurity/osim/assets/29104825/a152d9ec-da30-42a8-b5a7-008c15f0e69c
=> Task OSIDB-2912: Support private flaw comments

CHANGELOG.md, src/composables/useFlawModel.ts
When we create a Flaw, we navigate to the _edit view_ before saving the `cvss_score`, the _edit view_ fetches the flaw from osidb and if the request to save the `cvss_score` is not finished, it arrives with the `cvss_scores` empty, having to reload the page to be able to see it.
Reorganized the async steps after flaw creation to navigate only after all the requests are made.
If the flaw fails to be created, the navigation is aborted, but if the flaw creation succeeds the navigation is performed even if any of the extra requests fails, like it did before
=> OSIDB-2981: Refresh flaw after CVSS scores on create

CHANGELOG.md, src/views/FlawEditView.vue
`key` property is needed for vue to detect reactive changes and update components properly, without it, only active references are updated.
Inside `useFlawAffectsModel` we are looping over the flaw affects and adding a `watch` to detect changes
https://github.com/RedHatProductSecurity/osim/blob/8a9a0dc28145cc6142647b4a600061b4730371ce/src/composables/useFlawAffectsModel.ts#L151
After the flaw is updated, the event `refreshFlaw` is emitted, this fetches the latest flaw version from OSIDB and updates the `flaw.value` reference. https://github.com/RedHatProductSecurity/osim/blob/8a9a0dc28145cc6142647b4a600061b4730371ce/src/views/FlawEditView.vue#L21-L25
Because the loop in `useFlawAffectsModel` is not inside a `watch` that detects changes to the flaw `reference` its only called once, and …
=> OSIDB-2948: Update FlawEditView.vue with key binding for flaw updates

CHANGELOG.md, src/components/AffectedOfferingForm.vue
We were adding this default value to any affect that didn't have a `cvss_score`, triggering the `trackAffectChanges` hook and updating all the affects when saving the flaw. I've done some testing and removing it doesn't seems to break anything but I may be missing something, already discussed with @superbuggy
=> OSIDB-2946: Unmodified affects are updated

CHANGELOG.md, src/components/FlawComments.vue, src/views/FlawEditView.vue
- [-] Test cases not added/updated
Temporary disables private comment creation until it is supported from OSIDB side.
- Disable comment creation button on private comments tab
- Add a tooltip to inform users that the action is temporary disabled disabled
- Hide comment creation input text area on private comments tab
- Didn't add reasons on the changelog as we are providing the ticket where all the info can be found
=> Task OSIDB-3002: Disable private comment creation

CHANGELOG.md, src/components/FlawComments.vue
Re-enables private comment creation on edit flaw form as OSIDB part to handle the `is_private` parameter has been already completed and deployed.
- Enable comment creation button on private comments tab
- Removes tooltip to inform users that the action is temporary disabled disabled
- Shows comment creation input text area on private comments tab
- Relates to: [OSIDB-3002: Disable private comment creation](https://github.com/RedHatProductSecurity/osim/pull/307)
=> Task OSIDB-3012: Enable private comments creation

CHANGELOG.md, src/components/IssueQueue.vue, src/components/IssueQueueItem.vue, src/components/Navbar.vue, src/components/__tests__/IssueQueue.spec.ts
Fixes text overlaps on flaw queue when status value is `PRE_SECONDARY_ASSESSMENT` by making the table larger in width.
Additionally adds a couple of minor UI/UX enhancements that were considered after this change.
- Increases flaw queue table's width
- Adjust spacing on navbar to for aesthetics
- Make loading/loaded flaws indicator act like a single element
- Removes unused code
- Before:
- After:
- Before:
[OSIM-LoadingIndicator-Before.webm](https://github.com/RedHatProductSecurity/osim/assets/29104825/bff773cf-8e64-4893-accb-59089775a235)
- After:
[OSIM-LoadingIndicator-After.webm](https://github.com/RedHatProductSecurity/osim/assets/29104825/3ffc88fb-81b8-40aa-9203-0ff421b5e626)
- Loading/loaded flaws indicator is covered if there are some alerts, may be we may consider relocating
- …
=> Fix OSIDB-2827: Flaw list text overlap

CHANGELOG.md, src/components/AffectedOfferingForm.vue, src/components/__tests__/AffectExpandableForm.spec.ts
📝 Update change log
* Limits Affect resolution selections based on affectedness value (`OSIDB-2787`)
- `NEW`, `NOTAFFECTED`  are limited to Empty (`''`)
- `AFFECTED` affectedness affects (lol) can be `DELEGATED`, `OOSS`, or `WONTFIX`
=> ✨ Restrict affect resolution choices based on affectedness

CHANGELOG.md, src/components/FlawForm.vue, src/components/IssueFieldState.vue, src/composables/useFlawModel.ts, src/services/FlawService.ts, src/services/OsidbAuthService.ts
Adds a button to create and associate a jira task to a flaw that does not have one
* Handle the new  `EMPTY` state when a Flaw does not have a Jira task associated
* Hide workflow buttons on `EMPTY` state
* Add a new `Create Jira Task` button.
---
OSIDB Added a boolean query param `create_jira_task` to the update flaw endpoint that forces the creation in https://github.com/RedHatProductSecurity/osidb/pull/603
https://github.com/RedHatProductSecurity/osim/assets/4268580/15b2ca5e-0b21-41cf-a6c2-2a10f331aa58
=> OSIDB-2883: Enable jira task creation on legacy flaw

CHANGELOG.md, src/components/FlawContributors.vue, src/components/FlawForm.vue, src/components/__tests__/FlawContributors.spec.ts, src/composables/__tests__/useJiraContributors.spec.ts, src/composables/useJiraContributors.ts, src/services/JiraService.ts, src/types/zodJira.ts
Added the `Contributors` field from Jira to OSIM
> Censored for privacy reasons. There's an uncensored video attached to the jira ticket
~While working on this task I got the `[object Object]` error and added the missing `return` that fixes the issue when osidb returns html (i.e stack trace of error).~ Fixed in https://github.com/RedHatProductSecurity/osim/pull/308
Created new `FlawContributors` component, is similar to the `TagsInput` widget, decided not to reuse the component because the auto-suggestions behavior is hard to implement in a reusable way. All the logic is inside the `useJiraContributors` composable.
I've added a generic type parameter to the `jiraFetch` function in `JiraService` so we can type the response easily, as well as some basic zod schemas and types for the …
=> OSIDB-2916: Add Contributors field

CHANGELOG.md, src/components/AffectedOfferings.vue, src/components/__tests__/AffectedOfferings.spec.ts
A ref mirroring the prop containing the list of affects is watched in order to update the list of expanded modules. This watcher did not fire when the component initially receives this data, and the list of expanded affects did not update
- Fire the watcher function on load.
- Add test coverage for Expand/Collapse All buttons
=> 🐛 Ensure Expand All button shows on load

src/components/IssueQueueItem.vue
- Provide badge for unembargoed flaws 
- Prevent edge case embargo label showing when flaw isn't embargoed (invalid data)
=> ✨ Provide label for unembargoed flaws

CHANGELOG.md
* Create Jira task on demand for legacy flaws (`OSIDB-2883`)
* Jira contributors field is now displayed on the Flaw form (`OSIDB-2916`)
* Hover style on Cvss Calculator buttons (`OSIDB-2511`)
* Temporary disable private comments creation (`OSIDB-3002`)
* Enable private comments creation again (`OSIDB-3012`)
* Highlight form style for embargoed flaw (`OSIDB-2984`)
* Added Cvss Score value to Cvss Vector field (`OSIDB-2511`)
* Flaws without a Jira task cannot be updated (`OSIDB-2960`)
* Remove Trackers section on Flaw Edit (`OSIDB-2954`)
* Owner - Status text overlap on flaw list (`OSIDB-2827`)
* Fix Error for Duplicated Affects (`OSIDB-2894`)
* Missing Expand All button on initial Flaw load (`OSIDB-3024`)
* Formatting for Tracker table timestamps (`OSIDB-2983`)
* Inconsistent focusing on …
=> 🔖 Increment version for v2024.6.2 release

CHANGELOG.md, src/composables/useFlawAttributionsModel.ts
Fix for the `afterSaveSuccess` callback when the first attribution was created on multiple creation, refreshing the flaw and making the form enabled again when attributions were still on creation process.
- Handle `afterSuccess` on `useFlawAttributionModel` after all specific attribution operations are completed (e.g. creating multiple references)
- Multiple delete operation on attributions is not supported
- For future improvement, would be nice to keep collapsibles state after refresh
https://github.com/RedHatProductSecurity/osim/assets/29104825/8fc2c7f5-d31a-4a9a-b567-f62eac9aee50
https://github.com/RedHatProductSecurity/osim/assets/29104825/bcc835dd-a629-4657-ad61-eade376c5aa2
=> Fix OSIDB-3066: Refresh multiple created attributions

src/composables/useTrackers.ts
- Closes OSIDB-3074
- Closes  OSIDB-3065
=> 🐛 Fix logic for excluding filed trackers from tracker selections

.github/pull_request_template.md, .github/workflows/jira.yaml
This PR adds a new github action that enforces the use of `Closes OSIDB-1234` or `Fixes OSIDB-1234` for linking the PR with Jira.
Added a comment to the PR template that reminds the user to add the tag as well.
In case that the PR does not have a Jira task associated, add the `internal` label to skip the check
=> Enforce jira link on pull requests

CHANGELOG.md, src/components/AffectExpandableForm.vue, src/components/AffectedOfferings.vue, src/components/AffectsTrackers.vue, src/components/CvssCalculator.vue, src/components/CvssExplainForm.vue, src/components/CvssNISTForm.vue, src/components/FlawAlert.vue, src/components/FlawAlertsList.vue, src/components/FlawAlertsSection.vue, src/components/FlawComments.vue, src/components/FlawForm.vue, src/components/FlawFormOwner.vue, src/components/IssueFieldReferences.vue, src/components/IssueFieldState.vue, src/components/__tests__/FlawForm.spec.ts, src/components/widgets/EditableList.vue, src/components/widgets/LabelDiv.vue, src/components/widgets/LabelEditable.vue, src/components/widgets/LabelInput.vue, src/components/widgets/LabelSelect.vue, src/components/widgets/LabelStatic.vue, src/components/widgets/LabelTagsInput.vue, src/components/widgets/LabelTextarea.vue, src/components/widgets/TagsInput.vue
Remove whitespace on OSIM's UI make a better use of the space available in every view aiming for a compact style.
- Make flaw form larger width
- Adjust form elements for a compact inline style
- Optimize space on text area fields section (descriptions)
- Make text area fields always visible (and remove buttons)
- Sightly adjust spacing on flaw attributions
- Minor UI corrections for affects sections
- Minor spacing adjustment between affect items
- Sightly adjust spacing on comments section
- Depends on [OSIM-288](https://github.com/RedHatProductSecurity/osim/pull/288)
- Also asked for feedback on the demo to users
- I considered toggling text area descriptions is not required anymore as with new layout the space is already compact
- Considered to make the embargoed highlighted border …
=> Style OSIDB-2005: UI Space optimization

CHANGELOG.md
* Make text area descriptions layout static (always visible) (`OSIDB-2005`)
* Missing references and/or acknowledgements after multiple creation (`OSIDB-3066`)
* Form is not disabled during multiple references and/or acknowledgements creation (`OSIDB-3066`)
* Exclude empty state from open issues filter (`OSIDB-3067`)
* Affect CVSS scores could not be edited (`OSIDB-3042`)
* Some affects' trackers were not showing (`OSIDB-3065`, `OSIDB-3074`)
* Remove extra whitespace and optimize UI spacing (`OSIDB-2005`)
* Remove buttons to show/hide text area descriptions (they are always visible now) (`OSIDB-2005`)
=> 🔖 Increment version for v2024.7.0 release

CHANGELOG.md, src/components/FlawForm.vue
When a Flaw does not have alerts, the `Open in bugzilla` link overlaps with the workflow actions because of the absolute positioning
Closes OSIDB-3089
=> Fix absolute positioning of bugzilla link

src/services/__tests__/osidb-errors-helpers.spec.ts, src/services/osidb-errors-helpers.ts
When the DEBUG mode is disabled (like in production) Django returns a generic `Server error` HTML body that didn't match our parser and a `undefined` was shown instead. Added a generic default message for that case.
For now this message is enough, in a future release we could add a `Contact` page to OSIM with links to email/slack channels for help and point to that page in the error message
Closes OSIDB-3080
=> ✨ Provide fallback values for unparsed errors

CHANGELOG.md, build/entrypoint.d/30-reverse-proxy.sh, src/services/JiraService.ts
Fix internal comment creation on chrome browsers by moving the User-Agent header definition (Prod only) from the `JiraService` to the nginx reverse proxy. 
User-Agent header needs to be set to a dummy value or removed for some requests to work on Jira REST API:
[REST API calls with a browser User-Agent header may fail CSRF checks](https://confluence.atlassian.com/jirakb/rest-api-calls-with-a-browser-user-agent-header-may-fail-csrf-checks-802591455.html)
[REST API request fails with XSRF check failed](https://community.developer.atlassian.com/t/rest-api-request-fails-with-xsrf-check-failed/22025)
We set the User-Agent header to "OSIM" in the JiraService (`osimRequestHeaders` method), as it is supposed that all headers from the original request are passed …
=> 🐛 Fix OSIDB-3091: Internal comments creation fail on Chrome browser

CHANGELOG.md, src/components/IssueQueue.vue
Removes duplicated spinner indicator on flaw queues when loading flaws
- Removes duplicated code
Closes OSIDB-3092
Before:
After:
=> 🐛 OSIDB-3092: Remove duplicated loading spinner

CHANGELOG.md, src/components/widgets/EditableList.vue
- Fix for the issue of not auto committing attributions being edited when changing to edit a new one.
Also applying minor enhancements for modified items logic, and styling.
Closes OSIDB-2905
- Adds a watcher to `EditableList` that auto-commits the changes if switching edit mode between items.
- Changes logic to consider a item has been modified when it differs with the saved values (previously compared with `priorValues`)
- Adjust items card styling
- `priorValues` are still needed for revert changes on `cancel` actions
https://github.com/RedHatProductSecurity/osim/assets/29104825/a8119a2a-814c-45a3-8696-363edc84057e
https://github.com/RedHatProductSecurity/osim/assets/29104825/64a4b09d-5851-4a19-a3a7-02e810c9c133
Closes OSIDB-2905
=> Fix OSIDB-2905: Edited references not commited

CHANGELOG.md, src/components/AffectedOfferingForm.vue, src/components/__tests__/AffectExpandableForm.spec.ts, src/components/widgets/LabelSelect.vue, src/types/zodAffect.ts, src/utils/guards.ts
When the `affectedness` was changed, the `resolution` kept the previous value, only the available options where updated but not the affect model.
* Reset the `resolution` value when the `affectedness` is changed
* Simplify the logic by using the available `affectedness` and `resolution` enums
* Changed the empty value (`''`) to an `Empty` string so it's easier to differentiate empty vs undefined
* Added a validation to the `resolution` based on the possibles values. See https://github.com/RedHatProductSecurity/osidb/blob/master/osidb/constants.py#L61-L76
Closes OSIDB-3123
https://github.com/RedHatProductSecurity/osim/assets/4268580/c483d8ee-b05b-4c5f-a714-6616bf6d057e
=> OSIDB-3123: Invalid Affect Resolution

CHANGELOG.md, Dockerfile, build/entrypoint.d/20-osim-runtime-json.sh, docs/overview.md, src/App.vue, src/components/__tests__/AffectExpandableForm.spec.ts, src/components/__tests__/App.spec.ts, src/components/__tests__/FlawComments.spec.ts, src/stores/osimRuntime.ts
This PR removes dirty validation from build, from runtime.json, from tests and from footer in UI.
Closes OSIDB-3068.
=> Remove validation for dirty tag

CHANGELOG.md, src/composables/useFlawCvssScores.ts, src/services/FlawService.ts, src/types/zodFlaw.ts
Right now it is not possible to delete a flaw's CVSS score through OSIM. Even though there is a button to clear the field, when trying to save the flaw it will show an error saying that this field cannot be null.
With this commit, when clearing the CVSS score field and saving the flaw, it will delete the CVSS score through OSIDB's API, using the DELETE method.
Closes OSIDB-1843.
=> Allow deleting CVSS scores

CHANGELOG.md, src/components/AffectsTrackers.vue, src/composables/useFlawAffectsModel.ts, src/composables/useFlawModel.ts, src/composables/useTrackers.ts, src/types/zodFlaw.ts
Reorders save operations for updating flaws, flaw & affect component validation, refreshing for trackers.
- Change saving order
```diff
- Affects, Delete Affects, Flaw CVSS, Flaw
+ Flaw, Flaw CVSS, Delete Affects, Affects
```
- Added validations for presence of Flaw `components` in its affected offerings 
-  Refresh trackers after filing trackers
Merge into stage for testing.
Closes OSIDB-3049.
Closes OSIDB-3099.
=> Reorder Flaw update saving operations

src/composables/useFlawAffectsModel.ts
From the [Vue documentation](https://vuejs.org/guide/essentials/watchers#deep-watchers): 
>When you call watch() directly on a reactive object, it will implicitly **create a deep watcher**
Because the top level watch was a `deep` watch, each time the affects were modified, it will trigger and run the `unwatch` stopping the `trackAffectChange` from being run, so the variable `didAffectsChange` was never updated.
Link to a playground to reproduce the error: https://play.vuejs.org/#eNqFU02PmzAQ/SsjXwJaRDZtTymJul3l0B7aqu0tzsGFIfHG2AibJBLiv3ewQxZpV7s3Zua9x5sPd+yhrtNTi2zJMps3snZg0bX1mmtZ1aZx0EGDZQJn4fID9FA2poIZMWZc50ZbB6USZ1gNqKjjGkCUJebOLmHbgSyWsIB+l3Ddx1yPFNeI/PjgcY8HofdI/CjwYlitwesMUKMwVWZ/raWyIJF+0FHogiW0xN3uuPZRNJhJT0K1mF59JKOyfV16Vkpy5NkzUgcoTQNR8NkGVTDl+LM4CMBYijyFLN36Tom/EVSZNnRlp3VrD1Eg …
=> OSIDB-3154: Use a shallow watch

src/composables/useFlawAffectsModel.ts
Variable `affectsToUpdate` was never used
Closes OSIDB-3154
=> OSIDB-3154: Affects with changes were not updated

CHANGELOG.md, src/components/IssueSearchAdvanced.vue, src/components/Navbar.vue, src/components/__tests__/FlawSearchView.spec.ts, src/components/__tests__/IssueSearchAdvanced.spec.ts, src/components/widgets/LabelCheckbox.vue, src/composables/__tests__/useSearchParams.spec.ts, src/composables/useFlawsFetching.ts
Due to a bug there are lot of flaws with empty CVE Description on Requested status, which difficult the work of users as it is generally expected to receive flaws with non empty description when looking for status Requested.
Adds support for searching flaws with non empty CVE description on `AdvancedSearch` view as a workaround for users search queries. It is provided a checkbox on Advanced search which modifies the CVE Description Field setting the value to `nonempty` which triggers the param for the OSIDB request.
- Adds a checkbox `Non empty CVE description` on advanced
- Supports `nonempty` value for CVE Descriptions params
https://github.com/user-attachments/assets/60a0e04c-fc48-4d3b-a109-7ab1a592213e
- There probably are cleaner ways to do this …
=> Feature OSIDB-3138: Search non empty CVE description

CHANGELOG.md, src/components/widgets/LabelTextarea.vue
Fix regression issue on text-area description fields and the focus highlight - label overlap
- Fix inheritable classes on text-area widget
- Fix text-area focus highlight label overlap
Closes OSIDB-3174
=> 🐛 Fix: Regression UI bug on textarea descriptions layout

CHANGELOG.md, src/components/AffectsTrackers.vue, src/components/__tests__/AffectsTrackers.spec.ts, src/composables/useTrackers.ts, src/services/TrackerService.ts
Shows a warning when untracked affects do not have any available trackers.
Compares a list of untracked affects with a list of available trackers. If any untracked affects do not have an available tracker, a warning is shown with the untrackable affect,
Closes OSIDB-3144. Closes OSIDB-3158.
=> ✨ Show untrackable affects in Trackers Manager

src/components/AffectsTrackers.vue
https://github.com/user-attachments/assets/32c6cfd9-4664-4e7a-938b-b72ee7bd433e
Makes untrackable affects alert collapsible, collapsed by default.
Making the list collapsed by default makes the layout less cluttered.
Closes OSIDB-3158.
=> 💄 Make untrackable affects alert collapsible

CHANGELOG.md, src/components/FlawComments.vue, src/components/FlawContributors.vue, src/components/FlawForm.vue, src/components/FlawFormOwner.vue, src/components/__tests__/FlawComments.spec.ts, src/components/__tests__/FlawContributors.spec.ts, src/components/__tests__/FlawFormOwner.spec.ts, src/components/widgets/JiraUser.vue, src/components/widgets/__tests__/JiraUser.spec.ts, src/components/widgets/__tests__/__snapshots__/JiraUser.spec.ts.snap, src/composables/__tests__/useJiraContributors.spec.ts, src/composables/useJiraContributors.ts, src/services/JiraService.ts, src/types/zodJira.ts
Filter out jira users that does not have access to the current project.
The endpoint `api/2/user/picker` does not allow to specify a task ID and returns all the jira users, currently there isn't an available endpoint from the public API that allows this kind of filtering while maintaining  the option to query by any part of the user (name, username or email).
I ended up using an internal endpoint `/internal/2/users/assignee` that allows filtering via task id and querying any part of the user (name, username or email)
I took the opportunity to do a small proof of concept about snapshot testing, so we can start using it from now on.
This kind of tests will prevent us for doing regressions like in #365 as they match the whole html tree of the component, so any change in classes, attributes …
=> OSIDB-3189: Filter jira users by task key

src/components/FlawForm.vue
`FlawFormOwner` prop is named `taskKey` but it was used as `task_key` in `FlawForm`
=> OSIDB-3189: Fix prop name

.gitignore, scripts/run_automation_test.sh
In preparation for sending the tests reports via email, I changed the `run_automation_test` script to add parameters to `behave` when running on the pipeline
Closes OSIDB-3214
=> OSIDB-3214: Save test reports as junit when on CI

CHANGELOG.md, src/types/zodAffect.ts
- [-] Test cases not added/updated
OSIM should allow users to save flaws even if there are affects with historical resolution values.
- Removes validation for resolution pairs in `ZodAffect`
I considered removing the existing `ZodAffect` validation, that way users wont be prevented to save flaws with historical affect, and users are still not able to create affects with invalid combinations cause historical options are hidden and also OSIDB handles it's own validation for that valid affects (which provides even more detailed information than OSIM was).
Closes OSIDB-3262
=> OSIDB-3262: Remove historical affects validation

CHANGELOG.md, src/components/AffectExpandableForm.vue, src/components/AffectedOfferingForm.vue, src/components/__tests__/AffectExpandableForm.spec.ts, src/composables/useTrackers.ts, src/types/zodAffect.ts, src/utils/helpers.ts, src/utils/typeHelpers.ts
Replaces WONTFIX with DEFER, as well as limits this selection to Affects with `LOW` impact. 
Makes possible affect resolutions dependent on impact value, dynamically calculations possible resolution values.
1. _**Depends on OSIDB-related subtasks and deployment of backend changes.**_
2.  @C-Valen  points out that
> ...that this merge will go before the affect section redesign, so it will be dependent on this (requiring adjustment from the new types and test cases).
> 
> #371
Closes OSIDB-3285. Closes OSIDB-3286. Closes OSIDB-3288.
=> Use DEFER in place of WONTFIX, restrict to LOW-impact Affects

CHANGELOG.md, src/components/AffectedOfferingForm.vue, src/components/__tests__/AffectExpandableForm.spec.ts, src/types/zodAffect.ts
Allow Affects with any impact to have DEFER resolution.
Removes validation that prevents higher than LOW severity affects to have DEFER.
Blessed be the users.
Closes OSIDB-3329.
=> ♻️ Remove validation for impact on DEFER affect resolution

package.json, postcss.config.cjs, src/main.ts, src/scss/bootstrap-customization.scss, src/scss/bootstrap-overrides.scss, src/scss/index.scss, yarn.lock
Fix Bootstrap imports and reduce CSS delivery
While working on fixing the CSS duplication, I discovered that the bootstrap scss overrides was broken and only worked because we had duplicate code.
The variable `$theme-colors` is an special variable that is expanded by bootstrap with the `utils.scss`, this file generates all the `text-[color]` classes (among others), because we were **overwriting** the map instead of **extending** it, all this classes failed to create, for example `text-dark`, **but** because we imported bootstrap twice, in `main.ts` and `index.scss` 
the classes `text-[color]` were created by the `main.ts` import before the `index.scss` overrides.
Bootstrap overrides needs to be declared before importing bootstrap, so all the variables defined with `!default` are not …
=> OSIDB-3227: Duplicated CSS

src/components/widgets/Toast.vue, src/components/widgets/__tests__/Toast.spec.ts, src/components/widgets/__tests__/__snapshots__/Toast.spec.ts.snap, src/stores/ToastStore.ts, src/utils/typeHelpers.ts
The Toast classes were generated dynamically by adding the severity (success, warning, danger...) to `text-bg-`. ie. `text-bg-success`
Dynamic class names are not supported with PurgeCSS because they can't be detected
- Created a mapping with the full class names
- Exported the types from `Toast` component to be reused in `ToastStore`
- Refactor the tests as they were throwing some pinia errors
Closes OSIDB-3359
=> OSIDB-3359: Fix toast colors after CSS purge

CHANGELOG.md, src/__tests__/helpers.ts, src/services/OsidbAuthService.ts, src/services/__tests__/OsidbAuthService.spec.ts, src/stores/UserStore.ts, src/stores/__tests__/UserStore.spec.ts, vitest.config.ts
Save access token in memory and use it until it is about to expire.
I added a 1 minute difference to account for clock shift, slow network or other possible problems
* Modified `UserStore` to save the `accessToken`
* Modified `getNextAccessToken` to check the store
Closes OSIDB-3373
=> OSIDB-3373: Reuse access token

CHANGELOG.md, src/components/IssueQueue.vue, src/components/__tests__/IssueQueue.spec.ts
The flaw list page allows the user to order the results in descending or ascending order by any of the fields in the header column. By default, it orders the results by created date in descending order (newest flaws first).
This commit adds the option to use the default ordering by OSIDB, by toggling between descending, ascending, and no order when clicking on a field in the header row. This is useful when using the search as OSIDB will return the results ordered based on relevancy. For example, when searching for a CVE, we may want to see the closest matches first, instead of the most recent flaws.
When clicking on a header field, instead of just toggling between descending and ascending order on that field, clicking it a third time will remove the ordering.
Closes OSIDB-3187.
=> Allow using default ordering in flaw list page

CHANGELOG.md, src/App.vue, src/components/__tests__/App.spec.ts, src/components/__tests__/__snapshots__/App.spec.ts.snap, src/views/IndexView.vue
Instead of fetching the flaws each time we mount the IndexView, we fetch them when the component is unmounted so the data is there the next time the user loads the view, leaving the caching of the state to the `KeepAlive` vue component
* Added `KeepAlive` component to the `RouterView` to "cache" `IndexView` component
* Used `onDeactivated` lifecycle hook on `IndexView` component to fetch flaws on unmount
* Refactor the `App` tests as they were fetching OSIDB and also throwing some warnings on the console
Closes OSIDB-3372
=> OSIDB-3373: Fetch flaws in the background to improve performance

CHANGELOG.md, src/components/IssueSearchAdvanced.vue, src/components/QueryFilterGuide.vue, src/components/__tests__/FlawSearchView.spec.ts, src/components/__tests__/IssueSearchAdvanced.spec.ts, src/composables/__tests__/useSearchParams.spec.ts, src/composables/useSearchParams.ts, src/views/FlawSearchView.vue
Provides support for query filters on advanced search using the new library implemented in OSIDB.
- Adds new optional input for the query filter on the advance search view
- Implement the logic for handling the query parameter on searchs or getting params
- Adapt test cases for advanced search by including new parameter
- Adds a modal for query guide and examples on advanced search 
- This is the base feature for advanced search redesign, and the first to be merged
Closes OSIDB-3088
=> ✨ Add query mode to advance search

CHANGELOG.md, src/components/FlawAffects.vue, src/components/FlawForm.vue, src/components/FlawTrackers.vue, src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap, src/composables/useFlawAffectsModel.ts, src/services/AffectService.ts
Fixes the bug of invalid CVSS field on the new affect section.
Implements the possibility to remove CVSS on affects.
- Fix affect's CVSS field
- Adjust affect table columns to correctly display CVSS vectors
- Adds truncation to flaw fields that have larger length than the table cell
- Adds the CVSS score to the affect CVSS vector when not editing it
- Implements the possibility to remove affect's CVSS
https://github.com/user-attachments/assets/253ab093-cbdd-4b5e-820e-d3fa7175fd3f
- Possibly impacting on https://github.com/RedHatProductSecurity/osim/pull/401 @superbuggy 
- affect cvss "model" logic was placed within the affect component for simplicity (also considering the component will be refactored), but an independent composable with that logic could be considered in the future.
Closes …
=> 🐛 Affects CVSS CRUD operations

CHANGELOG.md, src/components/IssueQueue.vue, src/components/__tests__/FlawSearchView.spec.ts, src/components/__tests__/IndexView.spec.ts, src/composables/useSearchParams.ts, src/stores/SearchStore.ts, src/views/FlawSearchView.vue, src/views/IndexView.vue
Add support to save query filter on user's default search store.
- Handles query filter if present when saving default search
- Displays query filter badge if present on active default filters from index view
- Fixes a bug where query filter field was not being set if present in router params
- Adapt test cases
- Depends on https://github.com/RedHatProductSecurity/osim/pull/397
Closes OSIDB-3387
=> ✨ Support saving query filter on default user search

src/__tests__/setup.ts, src/components/__tests__/App.spec.ts, src/components/__tests__/FlawComments.spec.ts, src/components/__tests__/Navbar.spec.ts, src/components/__tests__/__snapshots__/App.spec.ts.snap, vitest.config.ts
Some tests were indirectly calling the `setup` function of `osimRuntime` which tried to fetch `/runtime.json` and also OSIDB api.
Since `osimRuntime` only returns an object with runtime information, I decided to provide a global mock, fixing the network requests issues and also removing the need to manually mock it on each test when needed 
Configured vitest **setupFiles** for global test configuration.
Closes OSIDB-3416
=> OSIDB-3416: Mock osimRuntime globally

src/__tests__/helpers.ts, src/composables/__tests__/useSearchParams.spec.ts, src/composables/useSearchParams.ts
Created `useSetup` helper for testing composables that need lifecyle hooks.
Fixed `useSeachParams` tests
Using lifecycle hooks outside of Vue throws a warning on the console:
```
[Vue warn]: onMounted is called when there is no active component instance to be associated with.
Lifecycle injection APIs can only be used during execution of setup().
If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
```
The `useSetup` helper creates a volatile Vue app to mount the composable inside so the lifecycle hooks are triggered. This not only makes the test output cleaner but also the tests itself is more robust, as prior to this the lifecycle hooks were not triggering
> [!NOTE]
> Depends on the changes made to `FlawSearchView.spec.ts` in #400
Closes …
=> OSIDB-3415: Create `useSetup` helper for testing composables

src/__tests__/setup.ts, src/components/__tests__/App.spec.ts, src/components/__tests__/FlawAffects.spec.ts, src/components/__tests__/FlawComments.spec.ts, src/components/__tests__/FlawForm.spec.ts, src/components/__tests__/FlawTrackers.spec.ts, src/components/__tests__/Navbar.spec.ts, src/components/__tests__/__snapshots__/App.spec.ts.snap, src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap, src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap, src/services/__tests__/OsidbAuthService.spec.ts, vitest.config.ts
Some tests were not properly mocked and tried to reach the network.
Configured a global `msw` network server to catch al the requests and force test failure to assist in writing better tests.
From now on, instead of importing `setupServer` from `msw/node` you should import `server` from the setup and add your handlers with `server.use()`
* Created a global `msw` server
* Custom `onUnhandledRequest` callback to force fail the tests instead of just logging an error
* Fixed the tests that were failing after the changes
> [!NOTE]
> Branch created from #410 
> This needs to be merged after it
Closes OSIDB-3417
=> OSIDB-3417: Catch network requests on tests

src/components/FlawAffects.vue, src/components/FlawForm.vue, src/components/TrackerManager.vue
Fixes a bug on the affect section redesign, where trackers were not being refreshed after file tracker operations, forcing the users to manually refresh the page to see the changes.
- Add couple of missing types on `FlawForm`
- Fix emitters for affects refresh
https://github.com/user-attachments/assets/6a49c952-e95c-4f1d-b1e7-31c133436fd1
- Affects refresh indirectly refresh trackers aswell
- In the demo the refreshed tracker appears without `Bug ID` cause it was being used local OSIDB instance where those trackers didn't have `external_system_id`
Closes OSIDB-3427
=> 🐛 Fix trackers refreshing after file

CHANGELOG.md, src/components/FlawAffects.vue, src/components/FlawTrackers.vue, src/components/__tests__/FlawTrackers.spec.ts, src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap, src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap
Fixes incorrect mapping on the Modules and Stream columns on the trackers table (column values were swapped).
Also update test cases and introduce new unit test for tracker links and introduces a minor UX improvement.
- Add tooltip on affects modules with it's value
- Fix incorrect tracker module/stream columns values
- Update test cases for the change
- Update snapshots for the change
- Add new unit test for tracker links
- New affect modules cell tooltip is useful for when the modules are large and truncated, so users can see the full string value without goin to edit mode.
New tooltip:
Trackers column fix:
Closes OSIDB-3443
=> 🐛 OSIDB-3443: Fix wrong column mapping on trackers table

CHANGELOG.md, src/components/IssueSearchAdvanced.vue, src/components/__tests__/IssueSearchAdvanced.spec.ts, src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap, src/composables/useFlawsFetching.ts, src/stores/SearchStore.ts, src/views/FlawSearchView.vue, src/views/IndexView.vue
Allow search empty / nonempty on advanced search specific fields (ones supported by OSIDB).
- Removes previous checkbox and code for `cve_description` nonempty
- Adds conditional buttons for empty / nonempty searches on supported fields
- Changes empty param value from empty to word `isempty`
- Adds button to clear any advanced search field
- Adds button to clear query filter
- Updates test cases
- Empty field searches are now using param value `isempty`
- Non empty field searches remain using `nonempty`
- Depends on https://github.com/RedHatProductSecurity/osim/pull/398
Closes OSIDB-3389
=> ✨ Multifields emptiness advanced search support

src/components/CvssExplainForm.vue, src/components/FlawAffects.vue, src/components/FlawAlert.vue, src/components/FlawAlertsList.vue, src/components/FlawAlertsSection.vue, src/components/widgets/EditableList.vue, src/components/widgets/LabelCollapsible.vue
This pr fixes the problems of collapsible labels not working on local OSIM instances, by refactoring the `LabelCollapsible` component to always handle the collapsed state change events on the parent components.
- Refactor `LabelCollapsible` component to use always emits for state changes
- Update uses of `LabelCollapsible` component
https://github.com/user-attachments/assets/6c243f89-00ac-41b9-8f91-1d3d1ee4c671
- Considered the previously 'dual' way to handle collapse state changes (on parents or local) was aggregating unnecessary complexity, as in all the cases handle the events on the parent is possible.
- The components where the `LabelCollapsible` is used are:
- FlawAffects (modules filter)
- FlawAlerts (Alert, AlertList and …
=> 🐛 LabelCollapsible readonly error

package.json, src/App.vue, src/components/__tests__/IssueQueue.spec.ts, src/components/__tests__/Navbar.spec.ts, src/components/widgets/Toast.vue, src/composables/__tests__/useFlaws.spec.ts, src/stores/ToastStore.ts, src/stores/__tests__/SearchStore.spec.ts
Changed the `type-check` command to include test files and fixed all the type errors.
I tried all I could to override the types of the `node:timers` with the `dom` api to return a `number` instead of `NodeJS.Timeout` but nothing worked so at the end I updated the types
Closes OSIDB-3420
=> OSIDB-3420: Type checking on test files

package.json, src/components/IssueSearchAdvanced.vue, src/components/__tests__/IssueSearchAdvanced.spec.ts, yarn.lock
Because `djangoql-completion` uses normal DOM events to update the query, Vue wasn't aware of the changes when clicking the search button. Using my fork, I emit an **Input** event when the textarea changes, allowing Vue to detect the event and update the `v-model` accordingly. This fork also adds typescript support.
- replace `djangoql-completion` with `@mrmarble/djangoql-completion`
Closes OSIDB-3449
=> OSIDB-3449: Advanced search suggestions are not applied when using the mouse

src/__tests__/setup.ts
- ~Test cases added/updated~
Force test failure when console warn/error is called
Example:
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/2e9a80ed-bc84-40d8-b98b-1b006d8f1ccb)|![image](https://github.com/user-attachments/assets/0c56d21b-0a77-4ed1-bf28-3ff6ceb4cd05)\
If the tests needs to call console warn/error, you can override the spy:
```ts
vi.spyOn(console, 'error').mockImplementation(()=>{}); // Remove the `assert.fail`
console.error('something else') // <- This will not fail the test and also not print anything to the console
```
Closes OSIDB-3419
=> OSIDB-3419: Fail tests on console warn/error

CHANGELOG.md, src/components/FlawAffects.vue, src/components/FlawTrackers.vue, src/components/__tests__/FlawAffects.spec.ts, src/components/__tests__/FlawTrackers.spec.ts, src/components/__tests__/__snapshots__/FlawAffects.spec.ts.snap, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap
Adds new tooltips in the affect section redesign to display full string value on fields that can be truncated if too long.
- Adds new tooltips
- Update snapshots
- Adds tooltip tests
https://github.com/user-attachments/assets/e38728bf-0158-4c90-a43d-f26c715f27b9
Closes OSIDB-3453
=> OSIDB-3453: Add new tooltips for truncated fields

src/composables/useFlawsFetching.ts
- Fix for advance search, emptiness search.
- Adds missing string on `finializeRequestParams`
- No changelog update as advance search is not released yet
Closes OSIDB-3475
=> 🐛 OSIDB-3475: Add missing string on field emptiness search

src/components/IssueSearchAdvanced.vue, src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap
- [-] Jira ticket updated
Updates new advance search to remove irrelevant sorting fields based on internal discussion.
- Remove `cve_description` and `statement` from new sorting options on advance search results
- Updates snapshots
- Reason considered to remove those is that being a free text fields the sorting will be random, not providing to the users a useful ordering.
- Not reopening ticket just adding it as internal change.
=> 🔥 OSIDB-3388: Remove irrelevant sorting fields

CHANGELOG.md, src/components/FlawAffects.vue
Fixes an unintentional behavior of populating trackers table when adding new draft affects, which was being removed after saving it. 
- Does not consider trackers of new affects for the trackers table component
- Disable filing tracker button for non saved new affects
- In any case of filing tracker for non saved affect will throw error triggered by OSIDB response, the change of disabling the button just avoids confusing users
Closes OSIDB-3474
=> 🐛 OSIDB-3474: Dont populate trackers table on new affects

src/components/DjangoQLInput.vue, src/components/__tests__/__snapshots__/DjangoQLInput.spec.ts.snap
DjangoQL `autoResize` property disabled manually resizing the textArea 
Closes OSIDB-3481
=> OSIDB-3481: Allow users to resize advanced query input

CHANGELOG.md, src/composables/__tests__/useFlawCvssScores.spec.ts, src/composables/useFlawCvssScores.ts
The CVSS comment field explaining the difference between RH and NIST was only shown when both issuer had different scores.  The users complaint that after updating the scores to match, the field was hiding, making it impossible to remove the now unneeded explanation.
Added a condition to the `shouldDisplayEmailNistForm` variable that checks if the comment field is filled and shows it even when both issuer have the same score
Fixes OSIDB-3400
=> OSIDB-3400: Show CVSS comment field when there's a comment

CHANGELOG.md, src/components/IssueQueue.vue, src/components/__tests__/IssueQueue.spec.ts
Flaw creation date was using local timezone instead of UTC.
Because we only show dates (and no time) it wasn't obvious, but depending on the user timezone the date could change (i.e. `29-08-2024 22:05 UTC` = `30-08-2024 00:05 GMT+2`)
Added `toUtc` to `formattedDate` field
Closes OSIDB-3478
=> OSIDB-3478: Use UTC on flaw list

src/types/zodFlaw.ts
- [-] Jira ticket updated
Fixes validation errors when saving a flaw cause of the use of strict string on the history type on the zod flaw model.
- Use `any` type on the diff attribute for the history flaw zod model
=> 🐛 Fix flaw history validation issue

CHANGELOG.md, src/components/FlawAffects.vue
When an affect with delegated resolution was changed to have non affected affectedness, the resolution was kept as delegated, making it not valid and ending up with an error response form OSIDB when trying to save the flaw.
- Automatically resets resolution to an empty value when an affect's affectedness is set to non affected
Closes OSIDB-3533
=> 🐛 OSIDB-3533: Reset affects delegated resolution

CHANGELOG.md, src/components/FlawForm.vue, src/components/__tests__/FlawForm.spec.ts, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Fix BZ flaw link overlapping promotion button when no alerts are present
- Adds a "flaw header" div to have always a static space for header elements (even some of them are not present)
- Remove an unnecessary class
- Adjust vertical alignment of the BZ link
* Note: Also now the space between the flaw form and the top bar is always the same independently of the flaw header items displayed.
** In flaw creation that space is also the same.
Closes OSIDB-3592
=> 🐛 OSIDB-3592: Bugzilla link overlap on flaw state promotion button

CHANGELOG.md
* Add multi-flaw tracker filing (`OSIDB-3129`)
* Added new CVSS versions and issuers on flaw form (`OSIDB-3546`)
* Corrected BZ link overlapping flaw promotion button (`OSIDB-3529`)
* Allow empty impact on flaw (`OSIDB-3596`)
* Indicate affect module filters functionality more clearly (`OSIDB-3509`)
* Reflects component selections in Tracker Manager
* Reworked Affect Offering UI to make filtering functionality clearer
=> 📝 Update changelog for release

CHANGELOG.md, src/components/__tests__/FlawHistory.spec.ts, src/components/__tests__/__snapshots__/FlawHistory.spec.ts.snap, src/utils/helpers.ts
Small fix to correct the format of dates in the history section, which was in 12h.
As in all other dates we use 24h time format this will correct the parse function being used by the history section dates.
- Correct time format on `formatDateWithTimezone` helper function
- Adjust history test time to verify format is in 24h
Closes OSIDB-3645
=> 🐛 OSIDB-3645: Use 24h format on history dates

CHANGELOG.md, src/components/IssueQueue.vue, src/components/IssueSearchAdvanced.vue, src/components/__tests__/IssueQueue.spec.ts, src/components/__tests__/IssueSearchAdvanced.spec.ts, src/components/__tests__/Navbar.spec.ts, src/components/__tests__/__snapshots__/IssueSearchAdvanced.spec.ts.snap, src/composables/useSearchParams.ts, src/stores/SearchStore.ts, src/stores/__tests__/SearchStore.spec.ts, src/views/FlawSearchView.vue, src/views/IndexView.vue, src/views/__tests__/FlawSearchView.spec.ts, src/views/__tests__/IndexView.spec.ts, src/views/__tests__/__snapshots__/FlawSearchView.spec.ts.snap, src/views/__tests__/__snapshots__/IndexView.spec.ts.snap
Adds logic and UI adjustments to support multiple user saved searches.
- Updates `searchStore` to handle an array of searches
- Updates advance search components logic and UI to support loading, editing and removing saved searches
- Updates index view to display a list of saved searches
- Reduces initial query `textarea` height to be same as other input elements (still resizable)
- Adds support to set one saved search as favorite/default, so it is directly used on the issue queue of the index view
- Allows keeping draft advance search values so when deselecting a loaded saved search the previous 'non saved' search remains the same
- Blocks text selection on `summary` elements
- Changes naming of 'filters' to 'searches' for everything referencing to user saved searches
- Some code cleanup …
=> OSIDB-3137: Allow multiple user saved searches

CHANGELOG.md, src/components/FlawAffects/FlawAffectsTableRow.vue, src/composables/__tests__/useFlawAffectsModel.spec.ts, src/composables/useFlawAffectsModel.ts
- Variable `affectsCvssToDelete` was not considered when calculating `modifiedAffects`
- Added tests for `useFlawAffectsModel` composable
- Fixed z-fighting on the CVSS Calculator overlay
|before|after|
|---|---|
|![ezgif-5-1cca0c949c](https://github.com/user-attachments/assets/e5ee5dad-624e-451a-b5b5-6fd89b9b9395)|![ezgif-5-3e6fd8a961](https://github.com/user-attachments/assets/86a92b75-ada2-4e47-b7ad-1134e412891e)|
Closes OSIDB-3675
=> OSIDB-3675: Fix Unable to remove affect cvss

CHANGELOG.md, src/components/CvssSection/CvssSection.vue, src/views/__tests__/FlawCreateView.spec.ts
Fix to handle duplicated values on the CVSS displays.
Handles cases where vector values include CVSS version.
- Sometimes the vector values of third party CVSS come in already display format (i.e. includes CVSS + Version values in the vector string) In other cases the vector value is just the vector and the display string must be formed by OSIM. For this reasons it is required a conditional display, where the string is formed based in the CVSS vector value received from OSIDB.
- This does not happen for RH values, those are static so it was only needed to handle the values in the new collapsible section where third party CVSS are displayed.
Before:
After:
Closes OSIDB-3658
=> 🐛 OSIDB-3658: Fix incorrect CVSS displays

.github/dependabot.yml
By default Dependabot adds the dependencies label. Since we want the Dependabot PRs to skip the Jira pipeline, we need it to also add the internal label.
Related to OSIDB-3713
=> Configure Dependabot to add internal label

CHANGELOG.md, src/components/FlawTrackers/FlawTrackers.vue, src/components/__tests__/FlawTrackers.spec.ts
Fix  trackers status filter not working (always shows no results).
- Correct trackers status filter computed function
Closes OSIDB-3720
=> 🐛 OSIDB-3720: Fix trackers status filtering

CHANGELOG.md, src/components/FlawAffects/__tests__/__snapshots__/FlawAffects.spec.ts.snap, src/components/TrackerManager/TrackerManager.vue, src/widgets/TabsDynamic/TabsDynamic.vue
Allows user to not have to wait for query to finish when adding a related flaw CVE manually.
- Moves the loading indicator to the dropdown for adding a related flaw
--
Closes OSIDB-3739.
=> ✨ Enable manual flaw association in tracker manager during query

yarn.lock
Some packages (namely vite, vitest and msw) and their dependencies have been upgraded to more recent versions to solve vulnerabilities of high severity.
The packages and their dependencies have been upgraded while keeping the restrictions set in the `package.json`. These packages have not been upgraded to another major version to ensure no breaking changes are introduced.
Closes OSIDB-3716.
=> Upgrade some dependencies to more recent minor versions to address vulnerabilities

CHANGELOG.md, src/composables/useSearchParams.ts
Ascendant and descendant order by fields on the advance search were working the opposite way.
This fix corrects that,
- Switch `asc` and `desc` orders on useSearchParams
https://github.com/user-attachments/assets/49cd1d0c-0489-4432-b942-6ad72c33ff60
Closes OSIDB-3609
=> 🐛 OSIDB-3609 Fix advance search order by

CHANGELOG.md, src/components/FlawHistory/FlawHistory.vue, src/components/__tests__/FlawHistory.spec.ts, src/components/__tests__/__snapshots__/FlawHistory.spec.ts.snap, src/widgets/EditableDate/EditableDate.vue
Implementation of date range filter on the flaw history.
- Add support for history item filtering
- Allow custom placeholders on `EditableDate`
- Add date inputs for date range filtering
- Add button to clear filters
- Update `FlawHistory` test cases and snapshots
Closes OSIDB-3562
=> ✨ OSIDB-3562: Flaw history filtering

CHANGELOG.md
* Add component column to trackers table (`OSIDB-3721`)
* Warning when filing trackers on CVEs with low severity (`OSIDB-3429`)
* Date range filter on history (`OSIDB-3562`)
* Fix trackers status filter not working (`OSIDB-3720`)
* Fix duplicated values on CVSS displays (`OSIDB-3658`)
* Fix wrong advance search custom order (`OSIDB-3609`)
* Enable manual flaw association in Trackers Manager while query for related flaws resolves (`OSIDB-3739`)
=> 📝 Release 2024.12.0

CHANGELOG.md, src/components/FlawAffects/FlawAffectsTableRow.vue, src/components/FlawAffects/__tests__/FlawAffects.spec.ts
Affect resolution needs to be set to empty value when the affectedness is set to `NOTAFFECTED`. The bug was preventing this change to be automatic when changing an affect to `NOTAFFECTED`, forcing the users to manually set the resolution to empty prior to changing the affectedness.
- Move the `onChange` event designated to handle the automatic resolution change, from the affectedness option element to the the select element
- Add new test case to cover the bus scenario
- Depends on https://github.com/RedHatProductSecurity/osim/pull/478
https://github.com/user-attachments/assets/b8c0d0aa-d035-4d35-9b4d-a3cff7e6afda
Closes OSIDB-3708
=> 🐛 OSIDB-3708: Fix affect resolution on not affected changes

CHANGELOG.md, src/composables/useFlawAffectsModel.ts
CVSS was not being created on new affects on flaw save.
Extends a condition related to the affect CVSS to be created to consider also new affects.
https://github.com/user-attachments/assets/7fa93b5a-16e0-4b76-a90f-8ce082135d43
Closes OSIDB-3777
=> 🐛 Fix cvss not created on new affects

CHANGELOG.md, src/components/FlawAffects/__tests__/FlawAffects.spec.ts, src/components/FlawAffects/useFilterSortAffects.ts
Fix wrong sorting on affects table by Impact and Resolution
- Fix affects sorting comparator
- Add new test cases
Closes OSIDB-3480
=> 🐛 Fix affects impact and resolution ordering

build/entrypoint.d/32-mitre-proxy.sh
Quick fix for a missing character on the Mitre reverse proxy config.
=> 🐛 Mitre reverse proxy fix: Add missing character

CHANGELOG.md, src/composables/__tests__/useFlawCvssScores.spec.ts, src/composables/useFlawCvssScores.ts, src/services/FlawService.ts
CVSS Objects have an `embargoed` field independent from `Flaw.embargoed`, when a Flaw is unembargoed and the CVSS score is updated on the same action, the fields don't match and OSIDB returns an ACL error.
This change synchronizes both fields before CVSS update.
- Fixed CVSS embargo status
- Removed some weak types on the same files
Closes OSIDB-3861
=> [OSIDB-3861] CVSS embargoed status does not match Flaw

CHANGELOG.md, src/components/FlawAffects/FlawAffects.vue, src/components/FlawAffects/__tests__/FlawAffects.spec.ts, src/components/FlawAffects/__tests__/__snapshots__/FlawAffects.spec.ts.snap, src/components/FlawTrackers/FlawTrackers.vue, src/components/TrackerManager/TrackerManager.vue, src/composables/__tests__/useFlawAffectsModel.spec.ts, src/composables/__tests__/useRelatedFlawTrackers.spec.ts, src/composables/useFetchFlaw.ts, src/composables/useFlaw.ts, src/composables/useFlawAffectsModel.ts, src/composables/useFlawModel.ts, src/composables/useRelatedFlawTrackers.ts, src/services/FlawService.ts, src/services/OsidbAuthService.ts, src/stores/AffectsEditingStore.ts, src/stores/__tests__/AffectsEditingStore.spec.ts, src/stores/__tests__/DraftFlawStore.spec.ts, src/views/FlawCreateView.vue, src/views/FlawEditView.vue
=> 🐛 Refresh affect trackers after filing trackers

CHANGELOG.md, src/components/FlawAffects/FlawAffects.vue, src/components/FlawAffects/__tests__/FlawAffects.spec.ts, src/components/FlawAffects/__tests__/__snapshots__/FlawAffects.spec.ts.snap, src/components/FlawAffects/flawAffectConstants.ts, src/components/FlawTrackers/FlawTrackers.vue, src/components/__tests__/FlawTrackers.spec.ts, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/components/__tests__/__snapshots__/FlawTrackers.spec.ts.snap
New buttons to display all trackers/affects in a single page.
- Add new button feature to affect and trackers table
https://github.com/user-attachments/assets/38d868a4-fedb-4275-92f1-c67b118b6312
- When the show all is enabled the pagination controls are hidden
Closes OSIDB-3506
=> ✨ Show all affects button

CHANGELOG.md, src/components/FlawAffects/__tests__/FlawAffects.spec.ts, src/components/__tests__/FlawTrackers.spec.ts, src/composables/usePaginationWithSettings.ts
Changing the step value for the "Per page" actions on the trackers/affects tables.
- Changes the step value on the pagination composable
https://github.com/user-attachments/assets/257c7d3c-7a0c-4956-94ba-36b4b8f327e1
- Min/Max function are used to control the range limits (max items per page and min items per page)
Closes OSIDB-3508
=> ✨ Increase step value for items per page

CHANGELOG.md, src/assets/main.css, src/components/CweSelector/CweSelector.vue, src/components/FlawForm/FlawForm.vue, src/components/__tests__/CweSelector.spec.ts, src/components/__tests__/FlawForm.spec.ts, src/components/__tests__/__snapshots__/CweSelector.spec.ts.snap, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/services/CweService.ts, src/types/mitreCwe.ts, src/types/zodMitre.ts, src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Update for the OSIM UI to provide a CWE Selector using suggestions to help users.
Corrections in the Mitre service logic
- Corrects `CweService.ts` to use the proper data for weaknesses
- Adds new `CweSelector` component to be used in the flaw form
- Adds keyboard navigation to the dropdown menu
- Adds new test cases and update snapshots
- Depends on https://github.com/RedHatProductSecurity/osim/pull/521
Closes OSIDB-3743
=> ✨ Provide CWE Selector

CHANGELOG.md, src/components/FlawAffects/useFilterSortAffects.ts
~- [ ] Test cases added/updated~
Auto-sort causes new affects to be sorted which does not make sense and causes focus-loss.
Prevent focus-loss when editing new affects by exempting them from auto-sort 
Closes OSIDB-3972
=> 🐛 Fix sorting for new affects (don't sort them)

src/types/zodFlaw.ts
Removes or updates schema so that flaws wont be prevented from being saved by Zod encountering unexpected value types (strings) in the `history.pgh_context.user` field.
Closes OSIDB-3977
=> 🔧 Don't Validate FlawHistory with Zod

CHANGELOG.md, src/components/FlawForm/FlawForm.vue, src/components/__tests__/FlawForm.spec.ts, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Adds a link to Jira task if existing in the top right side of the flaw form view, just below the BZ link.
This requeriment appeared cause previously the only Jira link was on the internal comments, making it for read-only users who don't have an Jira API key set, difficult to quickly access to the related Jira task of a flaw.
- Adds the new Jira link on the flaw form view
Closes OSIDB-3964
=> ✨ Add global Jira link

CHANGELOG.md, src/App.vue, src/components/FlawComments/FlawComments.vue
Add in app message that will let users know that data input in this system will be transmitted to bugzilla thus
will be shared externally. Confirm completion and share evidence of
implementation.
- Add global toast for general Bugzilla data privacy notice
- Add specific banner on internal comments
- Requirement for PIA
Closes OSIDB-3997
=> 🔒️ In-app privacy notices

CHANGELOG.md, src/components/IssueQueue/IssueQueue.vue, src/components/IssueQueue/IssueQueueItem.vue, src/components/__tests__/IssueQueue.spec.ts, src/components/__tests__/__snapshots__/IssueQueue.spec.ts.snap, src/stores/SettingsStore.ts, src/stores/__tests__/SettingsStore.spec.ts, src/views/__tests__/__snapshots__/IndexView.spec.ts.snap
Instead of only showing 4 labels and hiding the rest behind a collapsible, show all the labels, wrapping them to the column
Added a `Hide labels` checkbox to optionally hide the labels, the setting is persisted in the storage
Closes OSIDB-3991
=> [OSIDB-3991] Show all flaw labels

CHANGELOG.md, src/components/FlawAffects/FlawAffects.vue, src/components/FlawAffects/__tests__/FlawAffects.spec.ts
Makes new affect rows added to the table directly in edit mode.
- Updates `addNewAffect` function to make the new affect in edit mode
- Small adjustment for the example names in the component and module of the new affect
- Adds new unit test case
- Specific request from stakeholders
Closes OSIDB-3953
=> 🚸 Add new affects in edit mode

CHANGELOG.md, src/components/FlawForm/FlawForm.vue, src/components/FlawLabels/FlawLabelsTable.vue, src/components/FlawLabels/__tests__/__snapshots__/FlawLabelsTable.spec.ts.snap, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Moves contributors table next to the affect section.
- Move contributors table
- Apply new style for section label
- Update snapshots
- New style for the label was a consideration to make the contributors section being easily visible between other sections, specially cause it is a collapsible section, and it was a bit difficult to locate with the previous section-label style.
Closes OSIDB-3995
=> 💄 Move contributors table before affect section

CHANGELOG.md, src/components/FlawForm/FlawForm.vue
On af49e86 we introduced a global "flaw store", with this, the flaw passed to `FlawForm` by props and the flaw used by `useFlawModel` refers to the same in-memory location.
When the flaw is updated by the `useFlawModel`, the watcher of `FlawForm` triggers, this watcher is calling `onReset` which updates the flaw in `useFlawModel`, triggering again the watcher and so on, creating an infinite loop, in large flaws, this loop crashes the browser.
This was detected to happen when the `Reset changes` button was clicked and when adding a reference, since that triggers a flaw update without updating the `updated_dt` so the view is not updated and thus, the watcher triggers
Here's a simplified workflow on what's happening, in $\color{lime}{\textsf{green}}$, the path …
=> [OSIDB-4026] Fix infinite loop on flaw update

CHANGELOG.md, src/components/FlawLabels/FlawLabelsContributor.vue, src/components/FlawLabels/__tests__/FlawLabelsContributor.spec.ts
Flaw label contributor can be removed
Added an `onBlur` event to the input that overrides the value if it is empty
Closes OSIDB-4014
=> [OSIDB-4014] Allow empty flaw label contributor

CHANGELOG.md, src/App.vue
It is annoying for the users that the privacy notice is shown every time OSIM is loaded. Is preferable to be shown only once to every user.
- Add a local storage variable to track if the privacy notice alert has been shown to an user
- With this change it is intended to show the notice alert only once
Closes OSIDB-4077
=> 🚸 Show privacy notice only once

CHANGELOG.md, src/components/FlawAffects/FlawAffectsTableRow.vue, src/components/FlawForm/FlawForm.vue, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Fix to prevent flaw form UI rebasing screen bounds when using large input values.
- Limit max width in affect section cells
- Limit max width in flaw form subdivisions (right/left divs)
- Update snapshots
- There was already ellipsis for overflow being applied but the width needed to be capped.
Closes OSIDB-4079
=> 🐛 Limit flaw form width

CHANGELOG.md, src/components/IssueQueue/IssueQueueItem.vue, src/components/__tests__/IssueQueue.spec.ts, src/components/__tests__/__snapshots__/IssueQueue.spec.ts.snap
Hides labels on the flaw queue view if they have already a contributor assigned.
So only labels without contributors are displayed.
- Adjust template for labels iteration
- Adds conditional render to labels on flaw queue
- Update test cases
I considered "display: none" method but the default vue conditional render looked proper and and fit better.
Closes OSIDB-3993
=> ✨   Hide labels that have contributor assigned

CHANGELOG.md, src/App.vue, src/components/Settings/Settings.vue, src/components/__tests__/ToastContainer.spec.ts, src/stores/SettingsStore.ts, src/stores/__tests__/SettingsStore.spec.ts, src/stores/__tests__/ToastStore.spec.ts
Refactors the use of localsotrage for the privacyNotice cookie to use the setting store of the user to fix issues with cache variables (API keys values getting overrived)
- Move privacyNotice cookie into settingsStore
- Update tests
- Couldn't replicate the issue so will need to get feedback from using on UAT
Closes OSIDB-4129
=> 🐛 Move privacyNotice cookie to settings store

CHANGELOG.md, src/components/FlawForm/FlawForm.vue, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Adds a link to CVE Page for flaws that have CVE ID present and are not embargoed.
- Adds the link in CVE ID input field label (conditional)
- Updates snapshots
https://github.com/user-attachments/assets/847b1e39-0cf3-4c66-9928-25a7761ea37e
Closes OSIDB-3118
=> ✨ CVE Page link

CHANGELOG.md, src/components/FlawComments/CommentList.vue, src/components/FlawComments/CommentsToolbar.vue, src/components/FlawComments/FlawComments.vue, src/components/FlawComments/NewCommentForm.vue, src/components/FlawForm/FlawForm.vue, src/components/__tests__/FlawComments.spec.ts, src/components/__tests__/__snapshots__/FlawComments.spec.ts.snap, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/composables/__tests__/useFlawCommentsModel.spec.ts, src/composables/useFlawCommentsModel.ts, src/constants/index.ts, src/stores/SettingsStore.ts, src/stores/__tests__/SettingsStore.spec.ts, src/types/index.ts, src/types/zodFlaw.ts, src/utils/helpers.ts, src/widgets/Tabs/Tabs.vue
Adding a new display mode to show all comment types under the same view. We are keeping previous display mode and allow users to choose their preference.
- Refactor `FlawComments` into smaller components for simplicity
- Relocate some comments constants/types to be globally available
- Add new single view for all comment types
- Support toggling between comments view modes
- Order comments by date descendant
- Use local storage for user display mode selection
- Make comments toolbar sticky
- Update tests
- Working on it, (having problems with Jira stage account)
- Comment toolbar sticky is mostly intended to allow users to use the view mode switch at any scroll point of the section 
- NTH - Custom comments order
Closes OSIDB-3467
=> ✨ Comments section display modes

features/pages/flaw_detail_page.py, requirements.txt
[OSIDB-4322] Change source in integration tests
`all_values[-1]` corresponded to "**XEN**" source which is hidden in the DOM and a recent Selenium version made this fail the test
Closes OSIDB-4322
=> [OSIDB-4322] Change source in integration tests

env.d.ts, index.html, package.json, src/App.vue, src/__tests__/setup.ts, src/components/__tests__/App.spec.ts, src/main.ts, src/scss/index.scss, src/stores/__tests__/osimRuntime.spec.ts, src/stores/osimRuntime.ts, src/types/zodOsim.ts, yarn.lock
During #583 we found a problem with how the `runtime.json` is loaded, we depend on this file for the backend urls, but the router runs first, which complicates token fetching since auth guards redirect to the login view
- Updated Vite to v6 to have access to `vite-ignore` property, vite 7 just released and might be too son to migrate.
- Added a `script type="module"` to load the `runtime.json`
Closes OSIDB-4334
=> [OSIDB-4334] Use a ES web module for runtime configuration

src/services/AffectService.ts
- ~[ ] Changelog updated~
- ~[ ] Test cases added/updated~
- ~[ ] Integration tests updated~
Corrects field name in url params
Corrects field name in url params
Closes OSIDB-4350
=> 🐛 Correct field name for affect fetching

src/components/CweSelector/CweSelector.vue, src/components/FlawAffects/__tests__/FlawAffects.spec.ts, src/composables/useFlawModel.ts, src/utils/helpers.ts, src/utils/typeHelpers.ts, src/widgets/LabelTagsInput/LabelTagsInput.vue, src/widgets/LabelTextarea/LabelTextarea.vue, src/widgets/TagsInput/TagsInput.vue
`errors` is a computed property that is updated every time the flaw changes, this means that the whole `FlawForm` is re-rendered, this introduces some performance issues in Flaws with a lot of affects. I've changed the `composed` to diff the errors and if nothing changed return the previous value which is already cached by Vue, reducing re-renders.
- Added `DeepMapValues` and `DeepNullable` type helpers
- Improved type definitions for `deepMap` helper
- Fixed flaw error propagation
- Fixed type errors that happened after tightening the definitions for the `error` prop 
Closes OSIDB-4272
=> [OSIDB-4272] Error propagation

CHANGELOG.md, src/components/FlawAffects/FlawAffectsTableRow.vue
OSIM generates affected component when PURL is provided in an affect to give users the value in advance (OSIDB also performs a parsing in the backend).
The parsing in OSIM side was not being equivalent to the one in OSIDB for some cases (OCI and RPMMOD type PURL), cause it needs special handling to add a namespace prior to the component name.
- Handle OCI and RPMMOD PURL type cases in parsing function
- This is taken as an immediate action to fix the bug, long term solution should go around OSIDB-4361
(handling parsing locally in each client)
Closes OSIDB-4358
=> 🐛 Fix PURL parsing component for OCI and RPMMOD types

CHANGELOG.md, src/components/Settings/Settings.vue, src/components/__tests__/Navbar.spec.ts, src/components/__tests__/ToastContainer.spec.ts, src/router/index.ts, src/services/ApiKeyService.ts, src/services/JiraService.ts, src/services/OsidbAuthService.ts, src/stores/SettingsStore.ts, src/stores/UserStore.ts, src/stores/__tests__/SettingsStore.spec.ts, src/views/__tests__/__snapshots__/SettingsView.spec.ts.snap
Instead, OSIM should send a PATCH /osidb/integrations request with the JIRA/BZ token the user has provided.
OSIM should not need to provide the BZ/JIRA HTTP headers when sending requests to OSIDB that require the user's BZ/JIRA tokens, OSIDB will fetch them automatically if the user has already stored them (if not stored, the server will reply with 400 Error so OSIM should still handle the case in which the user has not yet set their tokens).
For direct OSIM-JIRA integration, the user's tokens can be fetched with a GET /osidb/integrations request, the tokens should only be stored in-memory.
The tokens' values should not be displayed back to the user in the settings page.
- **Split settings storage**: API keys now saved securely on backend …
=> ✨ API Keys migration

CHANGELOG.md, src/router/index.ts, src/stores/SettingsStore.ts
Prevents incorrect "unset API keys" notifications from showing before actually trying to fetch them.
- Removed API key checks from router guards
- Centralized notification logic moved to `SettingsStore` initialization
- Only shows "unset keys" warning when actually needed (keys missing + not read-only mode)
- Eliminates false notifications during normal app navigation
Closes OSIDB-4390
=> 🐛 Fix incorrect unset API keys toast

CHANGELOG.md, src/components/FlawForm/FlawForm.vue, src/services/AffectService.ts
Fix the affects fetch which is currently limited to 100 by OSIDB default's limit.
Modifies `getAffects` to fetch affects in batches of 100 until `count` is  reached.
Quick change was just rising the limit on fetch affect request, but I considered this "batched" request more efficient.
Closes OSIDB-4393
=> 🐛 Fix limited affects fetch

CHANGELOG.md, src/App.vue, src/components/SessionWarningBanner/SessionWarningBanner.vue, src/components/__tests__/SessionWarningBanner.spec.ts, src/components/__tests__/__snapshots__/App.spec.ts.snap, src/composables/__tests__/useSessionWarning.spec.ts, src/composables/useSessionWarning.ts, src/services/OsidbAuthService.ts, src/stores/UserStore.ts
Adds a banner that shows up when the user's refresh token is about to expire (less than 1h left).
Supports extending user session (renewing refresh token by reauthenticating) from a button in the warning banner.
- Banner template
- Reauthentication logic
- Make refresh token available in memory
- Update tests
The `UserStore` changes in this branch are to make the refresh token available in memory to be able to check the expiring time and properly showing the banner.
Closes OSIDB-4275
=> ✨ Reauthentication banner

build/entrypoint.d/20-osim-runtime-json.sh, src/components/CweSelector/CweSelector.vue, src/components/__tests__/__snapshots__/CweSelector.spec.ts.snap, src/components/__tests__/__snapshots__/FlawForm.spec.ts.snap, src/types/zodOsim.ts, src/views/__tests__/__snapshots__/FlawCreateView.spec.ts.snap
Disabling CWE Aegis-AI suggestions for simplifying incoming OSIM releases.
Once Aegis backend is released to prod, we just need to remove the flag and release our side.
Would be nice to have an actual flag system that allow us to enable/disable features without requiring releases (As @MrMarble suggested a while ago)
=> 🚩 Disable CWE AI Suggestions

CHANGELOG.md, src/components/IssueQueue/IssueQueue.vue, src/components/__tests__/IssueQueue.spec.ts, src/components/__tests__/__snapshots__/IssueQueue.spec.ts.snap
Add times to dates in the Flaw index view.
Closes OSIDB-4407
=> Show creation times along with creation dates in Flaw view

CHANGELOG.md, src/components/__tests__/Navbar.spec.ts, src/components/__tests__/ToastContainer.spec.ts, src/stores/SettingsStore.ts
The problem: API keys didn’t load on fresh sessions due to non-reactive auth gating (isLoggedin was being changed to true after api keys initialization).
The solution: Wait for reactive isAuthenticated (via `waitUntilAuthenticated`), then load/migrate keys once.
- Add `waitUntilAuthenticated` in UserStore using VueUse `until`.
- `SettingsStore.initializeApiKeys` awaits auth, then loads/migrates keys.
- Removed non-reactive `isLoggedIn` gating
- Tested in dev and working
Closes OSIDB-4416
=> 🐛 API Keys not loaded on new user session

CHANGELOG.md, src/components/FlawAffects/FlawAffectsTableRow.vue, src/components/FlawAffects/__tests__/FlawAffectsTableRow.spec.ts
Fix a bug where affects CVSS cannot be edited or created from the overlayed calculator
- Corrects wrong references in the overlayed calculator component parameters
Closes OSIDB-4431
=> 🐛 Fix affects cvss not editable

src/widgets/DropDownMenu/DropDownMenu.vue, src/widgets/DropDownMenu/__tests__/DropDownMenu.spec.ts
Bootstrap `dropdown-menu` is very simple to use but lacks some functionality.
I've created a `DropDown` widget that utilizes the `Teleport` Vue component to render itself outside of the parent element, bypassing any issues with overflow styles.
Closes OSIDB-4470
=> [OSIDB-4470] Create `DropDown` widget

src/composables/__tests__/useAegisSuggestionContext.spec.ts, src/composables/aegis/useAegisSuggestionContext.ts
Adds cvss_scores, comments, affects, references, and embargoed fields to request to Aegis
=> Add fields to Aegis context requests

CHANGELOG.md, src/services/FlawService.ts
History included param was missing in flaw put request so the response didn't include it and it was becoming hidden after saving any changes.
- Ensure history is included on put flaw response
Closes OSIDB-4491
=> 🐛 Fix history hidden on flaw save

src/__tests__/__fixtures__/sampleFlawHistory.json, src/components/FlawHistory/FlawHistory.vue, src/components/__tests__/FlawHistory.spec.ts, src/components/__tests__/__snapshots__/FlawHistory.spec.ts.snap, src/composables/__tests__/useAegisSuggestCwe.spec.ts, src/composables/aegis/__tests__/useAegisMetadataTracking.spec.ts, src/composables/aegis/useAISuggestionsWatcher.ts, src/composables/aegis/useAegisMetadataTracking.ts, src/composables/aegis/useAegisSuggestCwe.ts, src/composables/useFetchFlaw.ts, src/composables/useFlawModel.ts, src/types/aegisAI.ts, src/types/zodFlaw.ts
Implement AI metadata tracking for Aegis suggestions in flaw history to flag AI-generated and user-modified AI changes.
- Send AI metadata to OSIDB when saving flaws with AI changes
- Added `aegis_meta` field to Flaw schema for tracking AI interactions
- Created composables for AI metadata tracking and suggestion watching patterns
- Refactored CWE suggestion logic to use new AI tracking system
- Display AI/Partial AI badges in flaw history with explanatory tooltips
- Hide internal `aegis_meta` field from history display
Closes OSIDB-4454
=> ✨ Aegis-AI History badges
